import type { LucideIcon } from "lucide-react";
import { AudioLines, Barcode, FileCheck2, FileImage, FileSpreadsheet, FileText, FileType2, PenLine, QrCode, ScanLine, ScanText, Video } from "lucide-react";

export type ToolCategory = "pdf" | "image" | "document" | "spreadsheet" | "ocr" | "code" | "sign" | "utility" | "audio" | "video";
export type ToolDefinition = {
  slug: string; category: ToolCategory; icon: LucideIcon; labelAr: string; labelEn: string;
  descriptionAr: string; descriptionEn: string; formats: string[]; accepts: string[];
  settings: Array<"quality" | "outputFormat" | "pages" | "rotation" | "flip" | "watermark" | "pageNumbers" | "dimensions" | "crop" | "blur" | "metadata" | "language" | "bitrate" | "trim" | "resolution" | "fps" | "password">;
  multi?: boolean; local: boolean; processingMode?: "local" | "server" | "hybrid"; experimental?: boolean; readiness?: "ready" | "improving" | "experimental";
};

const pdf = FileType2, image = FileImage, document = FileText, spreadsheet = FileSpreadsheet, ocr = ScanText, code = QrCode, sign = PenLine, utility = FileCheck2, audio = AudioLines, video = Video;
export const toolDefinitions: ToolDefinition[] = [
  { slug: "merge-pdf", category: "pdf", icon: pdf, labelAr: "دمج PDF", labelEn: "Merge PDF", descriptionAr: "اجمع ملفات PDF بترتيبك داخل جهازك.", descriptionEn: "Combine PDF files in your preferred order, locally.", formats: ["PDF"], accepts: ["application/pdf"], settings: [], multi: true, local: true },
  { slug: "split-pdf", category: "pdf", icon: pdf, labelAr: "تقسيم PDF", labelEn: "Split PDF", descriptionAr: "قسّم الملف إلى صفحات أو نطاقات مستقلة.", descriptionEn: "Split a PDF into individual pages or ranges.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["pages"], local: true },
  { slug: "extract-pdf-pages", category: "pdf", icon: pdf, labelAr: "استخراج صفحات PDF", labelEn: "Extract PDF pages", descriptionAr: "حمّل الصفحات التي تختارها في ملف مستقل.", descriptionEn: "Export selected pages into a new PDF.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["pages"], local: true },
  { slug: "delete-pdf-pages", category: "pdf", icon: pdf, labelAr: "حذف صفحات PDF", labelEn: "Delete PDF pages", descriptionAr: "احذف صفحات محددة محليًا قبل التنزيل.", descriptionEn: "Remove selected PDF pages locally.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["pages"], local: true },
  { slug: "reorder-pdf-pages", category: "pdf", icon: pdf, labelAr: "ترتيب صفحات PDF", labelEn: "Reorder PDF pages", descriptionAr: "اكتب ترتيب الصفحات المطلوب لتحصل على نسخة جديدة.", descriptionEn: "Set a custom page order and export a new PDF.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["pages"], local: true },
  { slug: "rotate-pdf", category: "pdf", icon: pdf, labelAr: "تدوير PDF", labelEn: "Rotate PDF", descriptionAr: "دوّر صفحات PDF بالزاوية التي تختارها.", descriptionEn: "Rotate PDF pages by the angle you choose.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["pages", "rotation"], local: true },
  { slug: "pdf-to-jpg", category: "pdf", icon: pdf, labelAr: "PDF إلى JPG", labelEn: "PDF to JPG", descriptionAr: "حوّل صفحات PDF إلى صور JPG.", descriptionEn: "Render PDF pages as JPG images.", formats: ["PDF", "JPG"], accepts: ["application/pdf"], settings: ["quality"], local: true },
  { slug: "pdf-to-png", category: "pdf", icon: pdf, labelAr: "PDF إلى PNG", labelEn: "PDF to PNG", descriptionAr: "حوّل صفحات PDF إلى صور PNG.", descriptionEn: "Render PDF pages as PNG images.", formats: ["PDF", "PNG"], accepts: ["application/pdf"], settings: ["quality"], local: true },
  { slug: "image-to-pdf", category: "pdf", icon: pdf, labelAr: "صور إلى PDF", labelEn: "Images to PDF", descriptionAr: "حوّل صورك إلى ملف PDF مرتب.", descriptionEn: "Build a sorted PDF from your images.", formats: ["JPG", "PNG", "WebP", "PDF"], accepts: ["image/*"], settings: [], multi: true, local: true },
  { slug: "compress-pdf", category: "pdf", icon: pdf, labelAr: "ضغط PDF", labelEn: "Compress PDF", descriptionAr: "أعد حفظ PDF بصيغة محسنة للملفات المدعومة.", descriptionEn: "Re-save compatible PDFs with optimized object streams.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["quality"], local: true },
  { slug: "watermark-pdf", category: "pdf", icon: pdf, labelAr: "إضافة علامة مائية", labelEn: "Add watermark", descriptionAr: "أضف نصًا فوق صفحات PDF.", descriptionEn: "Place custom text over PDF pages.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["watermark"], local: true },
  { slug: "page-numbers-pdf", category: "pdf", icon: pdf, labelAr: "ترقيم صفحات PDF", labelEn: "Page numbers", descriptionAr: "أضف أرقام صفحات واضحة لملفك.", descriptionEn: "Add readable page numbers to your PDF.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["pageNumbers"], local: true },
  { slug: "protect-pdf", category: "pdf", icon: pdf, labelAr: "حماية PDF بكلمة مرور", labelEn: "Protect PDF", descriptionAr: "أنشئ نسخة PDF محمية بكلمة مرور داخل جهازك.", descriptionEn: "Create a password-protected PDF copy on your device.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["password"], local: true, experimental: true },
  { slug: "unlock-pdf", category: "pdf", icon: pdf, labelAr: "فك حماية PDF", labelEn: "Unlock PDF", descriptionAr: "أنشئ نسخة بلا كلمة مرور عندما تملك كلمة المرور الصحيحة.", descriptionEn: "Create an unlocked copy when you have the correct password.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["password"], local: true, experimental: true },
  { slug: "crop-pdf", category: "pdf", icon: pdf, labelAr: "قص PDF", labelEn: "Crop PDF", descriptionAr: "اضبط إطار عرض صفحات PDF.", descriptionEn: "Adjust the visible crop box of PDF pages.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["crop"], local: true },
  { slug: "resize-pdf", category: "pdf", icon: pdf, labelAr: "تغيير مقاس PDF", labelEn: "Resize PDF", descriptionAr: "غيّر أبعاد صفحة PDF مع الحفاظ على المحتوى.", descriptionEn: "Change PDF page dimensions while keeping content.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["dimensions"], local: true },
  { slug: "flatten-pdf", category: "pdf", icon: pdf, labelAr: "تسطيح PDF", labelEn: "Flatten PDF", descriptionAr: "حوّل حقول النماذج القابلة للتعبئة إلى محتوى ثابت.", descriptionEn: "Flatten compatible interactive form fields.", formats: ["PDF"], accepts: ["application/pdf"], settings: [], local: true },
  { slug: "pdf-metadata", category: "pdf", icon: pdf, labelAr: "معلومات PDF", labelEn: "PDF metadata", descriptionAr: "اعرض أو امسح بيانات وصف PDF محليًا.", descriptionEn: "View or clear PDF document metadata locally.", formats: ["PDF"], accepts: ["application/pdf"], settings: ["metadata"], local: true },
  { slug: "preview-pdf", category: "pdf", icon: pdf, labelAr: "معاينة PDF", labelEn: "Preview PDF", descriptionAr: "اعرض ملف PDF داخل متصفحك قبل أي عملية.", descriptionEn: "Preview a PDF in your browser before any operation.", formats: ["PDF"], accepts: ["application/pdf"], settings: [], local: true },
  { slug: "convert-image", category: "image", icon: image, labelAr: "تحويل الصور", labelEn: "Convert images", descriptionAr: "حوّل JPG وPNG وWebP دفعة واحدة.", descriptionEn: "Convert JPG, PNG, and WebP in batches.", formats: ["JPG", "PNG", "WebP"], accepts: ["image/jpeg", "image/png", "image/webp"], settings: ["quality", "outputFormat"], multi: true, local: true },
  { slug: "compress-image", category: "image", icon: image, labelAr: "ضغط الصور", labelEn: "Compress images", descriptionAr: "خفّض الحجم مع تحكم واضح في الجودة.", descriptionEn: "Reduce image size with transparent quality control.", formats: ["JPG", "PNG", "WebP"], accepts: ["image/*"], settings: ["quality", "outputFormat"], multi: true, local: true },
  { slug: "resize-image", category: "image", icon: image, labelAr: "تغيير حجم الصور", labelEn: "Resize images", descriptionAr: "حدّد العرض والارتفاع مع الحفاظ على النسبة.", descriptionEn: "Set dimensions while preserving aspect ratio.", formats: ["JPG", "PNG", "WebP"], accepts: ["image/*"], settings: ["dimensions", "outputFormat"], multi: true, local: true },
  { slug: "crop-image", category: "image", icon: image, labelAr: "قص الصور", labelEn: "Crop images", descriptionAr: "قصّ الصورة بنسبة وإطار محددين.", descriptionEn: "Crop images to a defined box and ratio.", formats: ["JPG", "PNG", "WebP"], accepts: ["image/*"], settings: ["crop", "outputFormat"], local: true },
  { slug: "rotate-image", category: "image", icon: image, labelAr: "تدوير وقلب الصور", labelEn: "Rotate & flip", descriptionAr: "دوّر الصورة أو اقلبها أفقيًا وعموديًا.", descriptionEn: "Rotate or flip your image locally.", formats: ["JPG", "PNG", "WebP"], accepts: ["image/*"], settings: ["rotation", "flip", "outputFormat"], multi: true, local: true },
  { slug: "blur-image", category: "image", icon: image, labelAr: "تمويه جزء من الصورة", labelEn: "Blur part of an image", descriptionAr: "اختر يدويًا منطقة حساسة لتمويهها داخل جهازك.", descriptionEn: "Manually blur a sensitive region on your device.", formats: ["JPG", "PNG", "WebP"], accepts: ["image/*"], settings: ["blur", "outputFormat"], local: true },
  { slug: "txt-to-pdf", category: "document", icon: document, labelAr: "TXT إلى PDF", labelEn: "TXT to PDF", descriptionAr: "حوّل النصوص إلى PDF منسق.", descriptionEn: "Turn plain text into a formatted PDF.", formats: ["TXT", "PDF"], accepts: ["text/plain"], settings: [], local: true },
  { slug: "txt-to-docx", category: "document", icon: document, labelAr: "TXT إلى DOCX", labelEn: "TXT to DOCX", descriptionAr: "أنشئ ملف Word قابلًا للتحرير من النص.", descriptionEn: "Create an editable DOCX from plain text.", formats: ["TXT", "DOCX"], accepts: ["text/plain"], settings: [], local: true },
  { slug: "html-to-pdf", category: "document", icon: document, labelAr: "HTML إلى PDF", labelEn: "HTML to PDF", descriptionAr: "استخرج المحتوى النصي من HTML إلى PDF.", descriptionEn: "Convert HTML content to a text-first PDF.", formats: ["HTML", "PDF"], accepts: ["text/html", ".html"], settings: [], local: true, experimental: true },
  { slug: "rtf-to-pdf", category: "document", icon: document, labelAr: "RTF إلى PDF", labelEn: "RTF to PDF", descriptionAr: "حوّل نص RTF إلى PDF بأفضل نتيجة محلية.", descriptionEn: "Convert RTF text into a best-effort local PDF.", formats: ["RTF", "PDF"], accepts: ["application/rtf", ".rtf"], settings: [], local: true, experimental: true },
  { slug: "word-to-pdf", category: "document", icon: document, labelAr: "Word إلى PDF", labelEn: "Word to PDF", descriptionAr: "اعرض DOCX محليًا ثم صدّره إلى PDF بصريًا مع الصفحات والعناوين قدر الإمكان.", descriptionEn: "Render DOCX locally and export a visual PDF with pages and headings where supported.", formats: ["DOCX", "PDF"], accepts: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx"], settings: [], local: true, processingMode: "hybrid", readiness: "improving" },
  { slug: "pdf-to-word", category: "document", icon: document, labelAr: "PDF إلى Word", labelEn: "PDF to Word", descriptionAr: "استخرج النص إلى DOCX قابل للتحرير مع فصل الصفحات؛ استخدم OCR للملفات المصورة.", descriptionEn: "Extract text to editable DOCX with page separation; use OCR for scanned PDFs.", formats: ["PDF", "DOCX"], accepts: ["application/pdf"], settings: [], local: true, processingMode: "hybrid", readiness: "improving" },
  { slug: "xlsx-to-pdf", category: "spreadsheet", icon: spreadsheet, labelAr: "Excel إلى PDF", labelEn: "Excel to PDF", descriptionAr: "حوّل أوراق Excel المختارة إلى PDF جدولي محليًا.", descriptionEn: "Turn selected Excel sheets into a local table PDF.", formats: ["XLSX", "XLS", "PDF"], accepts: [".xlsx", ".xls", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.ms-excel"], settings: [], multi: true, local: true },
  { slug: "xlsx-to-csv", category: "spreadsheet", icon: spreadsheet, labelAr: "Excel إلى CSV", labelEn: "Excel to CSV", descriptionAr: "صدّر الأوراق المختارة من Excel كملفات CSV محلية.", descriptionEn: "Export selected Excel sheets as local CSV files.", formats: ["XLSX", "XLS", "CSV"], accepts: [".xlsx", ".xls", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.ms-excel"], settings: [], multi: true, local: true },
  { slug: "csv-to-xlsx", category: "spreadsheet", icon: spreadsheet, labelAr: "CSV إلى Excel", labelEn: "CSV to Excel", descriptionAr: "حوّل ملف CSV أو مجموعة ملفات إلى مصنف Excel محلي.", descriptionEn: "Turn one or more CSV files into a local Excel workbook.", formats: ["CSV", "XLSX"], accepts: [".csv", "text/csv"], settings: [], multi: true, local: true },
  { slug: "merge-excel", category: "spreadsheet", icon: spreadsheet, labelAr: "دمج ملفات Excel", labelEn: "Merge Excel files", descriptionAr: "ادمج الأوراق المختارة من عدة ملفات Excel في مصنف واحد.", descriptionEn: "Combine selected sheets from multiple Excel files into one workbook.", formats: ["XLSX", "XLS"], accepts: [".xlsx", ".xls", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.ms-excel"], settings: [], multi: true, local: true },
  { slug: "ocr", category: "ocr", icon: ocr, labelAr: "استخراج النص OCR", labelEn: "OCR text extraction", descriptionAr: "استخرج العربية والإنجليزية من الصور أو صفحات PDF المصورة.", descriptionEn: "Extract Arabic and English text from images or scanned PDFs.", formats: ["JPG", "PNG", "PDF", "TXT", "DOCX"], accepts: ["image/*", "application/pdf"], settings: ["language"], multi: true, local: true, processingMode: "hybrid", readiness: "improving" },
  { slug: "qr-generator", category: "code", icon: QrCode, labelAr: "إنشاء QR Code", labelEn: "QR Code generator", descriptionAr: "أنشئ QR للرابط والنص والاتصال وWi-Fi محليًا.", descriptionEn: "Create local QR codes for links, text, contact, and Wi-Fi.", formats: ["PNG", "SVG", "PDF"], accepts: [], settings: [], local: true },
  { slug: "qr-reader", category: "code", icon: ScanLine, labelAr: "قراءة QR Code", labelEn: "QR Code reader", descriptionAr: "اقرأ QR من صورة أو كاميرا داخل المتصفح.", descriptionEn: "Read QR from an image or camera in your browser.", formats: ["JPG", "PNG", "WebP", "TXT"], accepts: ["image/*"], settings: [], local: true },
  { slug: "barcode-generator", category: "code", icon: Barcode, labelAr: "إنشاء Barcode", labelEn: "Barcode generator", descriptionAr: "أنشئ Barcode موثوقًا مع تحقق من الصيغة.", descriptionEn: "Create a validated, printable barcode locally.", formats: ["PNG", "SVG", "PDF"], accepts: [], settings: [], local: true },
  { slug: "sign-pdf", category: "sign", icon: sign, labelAr: "توقيع PDF", labelEn: "Sign PDF", descriptionAr: "أضف توقيعًا بصريًا محليًا إلى PDF. ليس توقيعًا رقميًا معتمدًا.", descriptionEn: "Add a local visual signature to PDF. Not a certified digital signature.", formats: ["PDF", "PNG"], accepts: ["application/pdf"], settings: [], local: true },
  { slug: "file-hash", category: "utility", icon: utility, labelAr: "فحص سلامة الملف", labelEn: "File integrity checker", descriptionAr: "احسب SHA-256 وSHA-512 محليًا وقارن بصمة الملف.", descriptionEn: "Calculate local SHA-256 and SHA-512 file hashes.", formats: ["TXT"], accepts: ["*/*"], settings: [], local: true },
  { slug: "convert-audio", category: "audio", icon: audio, labelAr: "تحويل الصوت", labelEn: "Convert audio", descriptionAr: "حوّل الصيغ الصوتية محليًا عند الطلب.", descriptionEn: "Convert audio formats locally when you need it.", formats: ["MP3", "WAV", "M4A", "AAC", "OGG"], accepts: ["audio/*", ".m4a", ".aac", ".ogg"], settings: ["bitrate"], multi: true, local: true, processingMode: "hybrid", experimental: true },
  { slug: "trim-audio", category: "audio", icon: audio, labelAr: "قص الصوت", labelEn: "Trim audio", descriptionAr: "حدّد بداية ونهاية المقطع الصوتي.", descriptionEn: "Set the start and end of your audio clip.", formats: ["MP3", "WAV", "M4A", "AAC", "OGG"], accepts: ["audio/*"], settings: ["trim", "bitrate"], local: true, experimental: true },
  { slug: "merge-audio", category: "audio", icon: audio, labelAr: "دمج الصوت", labelEn: "Merge audio", descriptionAr: "ادمج ملفات صوتية متشابهة محليًا.", descriptionEn: "Merge compatible audio files locally.", formats: ["MP3", "WAV", "M4A", "AAC", "OGG"], accepts: ["audio/*"], settings: ["bitrate"], multi: true, local: true, experimental: true },
  { slug: "audio-metadata", category: "audio", icon: audio, labelAr: "معلومات الصوت", labelEn: "Audio information", descriptionAr: "استخرج حجم الملف ومدته ومعلوماته الأساسية.", descriptionEn: "Read file size, duration, and basic metadata.", formats: ["MP3", "WAV", "M4A", "AAC", "OGG"], accepts: ["audio/*"], settings: [], local: true },
  { slug: "video-to-mp3", category: "video", icon: video, labelAr: "فيديو إلى MP3", labelEn: "Video to MP3", descriptionAr: "استخرج الصوت من الفيديو محليًا.", descriptionEn: "Extract a local MP3 audio track from video.", formats: ["MP4", "WebM", "MOV", "MP3"], accepts: ["video/*"], settings: ["bitrate"], local: true, experimental: true },
  { slug: "mp4-to-webm", category: "video", icon: video, labelAr: "MP4 إلى WebM", labelEn: "MP4 to WebM", descriptionAr: "حوّل فيديو MP4 إلى WebM محليًا.", descriptionEn: "Convert MP4 video to WebM locally.", formats: ["MP4", "WebM"], accepts: ["video/mp4", ".mp4"], settings: [], local: true, experimental: true },
  { slug: "webm-to-mp4", category: "video", icon: video, labelAr: "WebM إلى MP4", labelEn: "WebM to MP4", descriptionAr: "حوّل فيديو WebM إلى MP4 محليًا.", descriptionEn: "Convert WebM video to MP4 locally.", formats: ["WebM", "MP4"], accepts: ["video/webm", ".webm"], settings: [], local: true, experimental: true },
  { slug: "compress-video", category: "video", icon: video, labelAr: "ضغط الفيديو", labelEn: "Compress video", descriptionAr: "خفّض الدقة والجودة بحسابات محلية.", descriptionEn: "Lower resolution and quality with local processing.", formats: ["MP4", "WebM", "MOV"], accepts: ["video/*"], settings: ["bitrate", "resolution", "fps"], local: true, processingMode: "hybrid", experimental: true },
  { slug: "trim-video", category: "video", icon: video, labelAr: "قص الفيديو", labelEn: "Trim video", descriptionAr: "حدّد جزءًا من الفيديو لمعالجته داخل الجهاز.", descriptionEn: "Trim a chosen section of your video locally.", formats: ["MP4", "WebM", "MOV"], accepts: ["video/*"], settings: ["trim", "resolution"], local: true, processingMode: "hybrid", experimental: true },
  { slug: "extract-frame", category: "video", icon: video, labelAr: "استخراج إطار", labelEn: "Extract video frame", descriptionAr: "احفظ لقطة من الفيديو كصورة PNG.", descriptionEn: "Save a video frame as a PNG image.", formats: ["MP4", "WebM", "MOV", "PNG"], accepts: ["video/*"], settings: ["trim"], local: true },
  { slug: "video-metadata", category: "video", icon: video, labelAr: "معلومات الفيديو", labelEn: "Video information", descriptionAr: "استخرج المدة والأبعاد ومعلومات الملف الأساسية.", descriptionEn: "Read duration, dimensions, and basic file metadata.", formats: ["MP4", "WebM", "MOV"], accepts: ["video/*"], settings: [], local: true },
];

export const categories: Array<{ id: ToolCategory; labelAr: string; labelEn: string; icon: LucideIcon; color: string }> = [
  { id: "pdf", labelAr: "أدوات PDF", labelEn: "PDF tools", icon: pdf, color: "violet" },
  { id: "image", labelAr: "أدوات الصور", labelEn: "Image tools", icon: image, color: "amber" },
  { id: "document", labelAr: "المستندات", labelEn: "Documents", icon: document, color: "blue" },
  { id: "spreadsheet", labelAr: "Excel والجداول", labelEn: "Excel & spreadsheets", icon: spreadsheet, color: "emerald" },
  { id: "ocr", labelAr: "استخراج النص", labelEn: "OCR", icon: ocr, color: "emerald" },
  { id: "code", labelAr: "QR وBarcode", labelEn: "QR & Barcode", icon: code, color: "violet" },
  { id: "sign", labelAr: "توقيع PDF", labelEn: "Sign PDF", icon: sign, color: "rose" },
  { id: "utility", labelAr: "أدوات مساعدة", labelEn: "Utilities", icon: utility, color: "sky" },
  { id: "audio", labelAr: "الصوت", labelEn: "Audio", icon: audio, color: "rose" },
  { id: "video", labelAr: "الفيديو", labelEn: "Video", icon: video, color: "cyan" },
];

export const findTool = (slug: string) => toolDefinitions.find(tool => tool.slug === slug);

/** Homepage promotion deliberately excludes code/sign utilities until their production interaction matrix is complete. */
export const featuredToolDefinitions = toolDefinitions.filter(tool => (tool.readiness || (tool.experimental ? "experimental" : "ready")) === "ready" && !["code", "sign", "utility", "audio", "video"].includes(tool.category)).slice(0, 6);
