import { beforeEach, describe, expect, it, vi } from "vitest";
import type { TrpcContext } from "../_core/context";
import { privateSubjectHash, processingWindowKey } from "../processing/contracts";

const dbMock = vi.hoisted(() => ({ select: vi.fn(), insert: vi.fn(), update: vi.fn() }));
vi.mock("../db", () => ({ getDb: vi.fn(async () => dbMock) }));
import { processingRouter } from "./processing";

const now = new Date();
const userContext = (id = 7, role: "user" | "admin" = "user") => ({ user: { id, openId: `user-${id}`, email: `user-${id}@example.com`, name: "User", loginMethod: "test", role, createdAt: now, updatedAt: now, lastSignedIn: now }, req: {} as TrpcContext["req"], res: {} as TrpcContext["res"] } as TrpcContext);
const enabledSettings = { serverProcessingEnabled: true, serverMaxFileMb: 10, serverRateLimitPerMinute: 1, temporaryRetentionHours: 24 };
const eligibleTool = { slug: "convert-image", category: "image", isActive: true, processingMode: "hybrid", sizeLimitMb: 10 };

function resultChain(rows: any[]) { const direct: any = Promise.resolve(rows); direct.limit = async () => rows; direct.orderBy = async () => rows; const selection = { limit: async () => rows, orderBy: async () => rows, where: () => direct }; return { from: () => selection }; }
function selectSequence(...sets: any[][]) { dbMock.select.mockImplementation(() => resultChain(sets.shift() || [])); }

describe("processing protected routes", () => {
  beforeEach(() => { vi.clearAllMocks(); dbMock.insert.mockImplementation(() => ({ values: vi.fn(async () => [{ insertId: 44 }]) })); dbMock.update.mockImplementation(() => ({ set: () => ({ where: vi.fn(async () => undefined) }) })); });
  it("blocks server create when server processing is disabled", async () => { selectSequence([{ ...enabledSettings, serverProcessingEnabled: false }]); await expect(processingRouter.createCaller(userContext()).create({ toolSlug: "convert-image", requestedMode: "hybrid", byteSize: 10, contentType: "image/png" })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" }); });
  it("rejects an unsupported server tool and excessive file size", async () => { selectSequence([enabledSettings], [{ ...eligibleTool, processingMode: "local" }]); await expect(processingRouter.createCaller(userContext()).create({ toolSlug: "convert-image", requestedMode: "hybrid", byteSize: 10, contentType: "image/png" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); selectSequence([enabledSettings], [eligibleTool], [], [{ code: "free", maxFileMb: 5, dailyOperations: 3 }]); await expect(processingRouter.createCaller(userContext()).create({ toolSlug: "convert-image", requestedMode: "hybrid", byteSize: 6 * 1024 * 1024, contentType: "image/png" })).rejects.toMatchObject({ code: "PAYLOAD_TOO_LARGE" }); });
  it("rejects rate-limit and quota exhaustion before creating a job", async () => { const key = processingWindowKey(new Date()); const hash = privateSubjectHash("user-7", `server:convert-image:${key}`); selectSequence([enabledSettings], [eligibleTool], [], [{ code: "free", maxFileMb: 10, dailyOperations: 3 }], [{ subjectHash: hash, hitCount: 1, windowExpiresAt: new Date(Date.now() + 60_000) }]); const rateCaller = processingRouter.createCaller(userContext()); await expect(rateCaller.create({ toolSlug: "convert-image", requestedMode: "hybrid", byteSize: 10, contentType: "image/png" })).rejects.toMatchObject({ code: "TOO_MANY_REQUESTS" }); selectSequence([enabledSettings], [eligibleTool], [], [{ code: "free", maxFileMb: 10, dailyOperations: 1 }], [], [{ userId: 7, planCode: "free", windowKey: key, operationCount: 1, serverBytes: 10 }]); await expect(processingRouter.createCaller(userContext()).create({ toolSlug: "convert-image", requestedMode: "hybrid", byteSize: 10, contentType: "image/png" })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("hides jobs from another standard user and exposes completed owned results only before expiry", async () => { const job = { id: 12, publicId: "job-owned-123", ownerUserId: 7, state: "completed", expiresAt: new Date(Date.now() + 60_000) }; selectSequence([{ ...job, ownerUserId: 8 }]); await expect(processingRouter.createCaller(userContext(7)).status({ publicId: job.publicId })).rejects.toMatchObject({ code: "NOT_FOUND" }); selectSequence([job], [], [{ purpose: "result", releasedAt: null }]); const status = await processingRouter.createCaller(userContext(7)).status({ publicId: job.publicId }); expect(status.resultAvailable).toBe(true); expect(status.resultUrl).toContain(job.publicId); });
  it("permits cancellation only to the owning user while queued", async () => { const job = { id: 15, publicId: "job-cancel-123", ownerUserId: 7, state: "queued" }; selectSequence([job]); await expect(processingRouter.createCaller(userContext(7)).cancel({ publicId: job.publicId })).resolves.toEqual({ success: true }); expect(dbMock.update).toHaveBeenCalled(); selectSequence([{ ...job, ownerUserId: 8 }]); await expect(processingRouter.createCaller(userContext(7)).cancel({ publicId: job.publicId })).rejects.toMatchObject({ code: "NOT_FOUND" }); });
});
