import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowRight, ShieldCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function AdminUsersPage() {
  const { user, loading } = useAuth(); const enabled = user?.role === "admin"; const users = trpc.admin.users.useQuery(undefined, { enabled, retry: false }); const userPlans = trpc.admin.userPlans.useQuery(undefined, { enabled, retry: false }); const setRole = trpc.admin.setPlatformRole.useMutation({ onSuccess: () => void users.refetch() }); const setPlan = trpc.admin.setUserPlan.useMutation({ onSuccess: () => { void userPlans.refetch(); toast.success("تم تعيين الخطة المستقبلية للمستخدم."); } });
  if (loading) return null;
  if (!enabled) return <main className="admin-denied"><ShieldCheck size={29}/><h1>إدارة المستخدمين محمية</h1><p>سجّل الدخول عبر OAuth بحساب مدير مصرح له للوصول إلى هذه الصفحة في الإنتاج.</p><Button onClick={() => startLogin()}>دخول مدير الإنتاج</Button></main>;
  const plansByUser = new Map((userPlans.data || []).map(item => [item.userId, item])); return <DashboardLayout><main className="admin-page" dir="rtl"><header className="admin-titlebar"><div><span className="admin-kicker"><UsersRound size={14}/>إدارة الوصول الإنتاجي</span><h1>المستخدمون والأدوار والخطط</h1><p>لا يمكن إضافة مستخدم يدويًا: يسجل المستخدم دخول OAuth أولًا، ثم يمكن لمدير المنصة إدارة دوره وخطته بسجل تدقيقي. لا يوجد دفع مفعّل.</p></div><Button variant="outline" asChild><Link href="/admin"><ArrowRight size={15}/>عودة لمركز التشغيل</Link></Button></header><section className="admin-panel"><div className="panel-head"><div><h2>مستخدمو المنصة</h2><p>أحدث 200 مستخدم فقط. لا تعرض هذه الصفحة محتوى الملفات أو عمليات المستخدم الخاصة.</p></div></div>{users.isLoading ? <div className="admin-loading">تحميل المستخدمين…</div> : <div className="user-admin-list">{users.data?.map(item => { const plan = plansByUser.get(item.id); return <div key={item.id} className="user-admin-row"><span className="user-avatar">{(item.name || item.email || "U").slice(0, 1)}</span><div><b>{item.name || "مستخدم بلا اسم"}</b><small>{item.email || "بدون بريد"} · آخر دخول {new Date(item.lastSignedIn).toLocaleDateString("ar-SA")}</small></div><label>دور المنصة<select value={item.role} disabled={setRole.isPending || item.id === user.id} onChange={event => setRole.mutate({ userId: item.id, role: event.target.value as "admin" | "user" })}><option value="user">مستخدم</option><option value="admin">مدير</option></select></label><label>خطة مستقبلية<select value={plan?.planCode || "free"} disabled={setPlan.isPending} onChange={event => setPlan.mutate({ userId: item.id, planCode: event.target.value as "free" | "basic" | "pro" | "business", status: "active" })}><option value="free">Free</option><option value="basic">Basic</option><option value="pro">Pro</option><option value="business">Business</option></select></label></div>; })}{!users.data?.length && <div className="admin-empty"><UsersRound size={22}/><b>لا يوجد مستخدمون مسجلون بعد</b><p>سيظهر كل مستخدم هنا فور اكتمال دخوله الآمن عبر OAuth.</p></div>}</div>}</section></main></DashboardLayout>;
}
