import PublicLayout from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { useLocale } from "@/contexts/LocaleContext";
import { downloadBlob, formatBytes } from "@/lib/file-utils";
import { hashFile, type HashAlgorithm } from "@/lib/hash-engine";
import { ArrowLeftRight, Check, Clipboard, Download, FileCheck2, Files, ShieldCheck, Upload, X } from "lucide-react";
import { useRef, useState } from "react";

type Hashes = Record<HashAlgorithm, string>;
type Mode = "single" | "compare";

export default function FileHashPage() {
  const { t } = useLocale();
  const [mode, setMode] = useState<Mode>("single"); const [primary, setPrimary] = useState<File>(); const [secondary, setSecondary] = useState<File>();
  const [primaryHashes, setPrimaryHashes] = useState<Partial<Hashes>>({}); const [secondaryHashes, setSecondaryHashes] = useState<Partial<Hashes>>({});
  const [progress, setProgress] = useState(0); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const primaryInput = useRef<HTMLInputElement>(null); const secondaryInput = useRef<HTMLInputElement>(null);
  const reset = () => { setPrimaryHashes({}); setSecondaryHashes({}); setProgress(0); setError(""); };
  const assign = (target: "primary" | "secondary", file?: File) => { if (!file) return; target === "primary" ? setPrimary(file) : setSecondary(file); reset(); };
  const calculateFor = async (file: File, offset: number) => { const sha256 = await hashFile(file, "SHA-256", value => setProgress(offset + value * 0.25)); const sha512 = await hashFile(file, "SHA-512", value => setProgress(offset + 0.25 + value * 0.25)); return { "SHA-256": sha256, "SHA-512": sha512 } as Hashes; };
  const compute = async () => { if (!primary || (mode === "compare" && !secondary)) { setError(t("اختر الملف أو الملفين أولًا.", "Choose the required file or files first.")); return; } setWorking(true); reset(); try { const first = await calculateFor(primary, 0); setPrimaryHashes(first); if (mode === "compare" && secondary) setSecondaryHashes(await calculateFor(secondary, 0.5)); } catch { setError(t("تعذر حساب البصمة في هذا المتصفح. جرّب ملفًا أصغر أو متصفحًا أحدث.", "The browser could not calculate the hash. Try a smaller file or newer browser.")); } finally { setWorking(false); setProgress(0); } };
  const primaryComplete = Boolean(primaryHashes["SHA-256"] && primaryHashes["SHA-512"]); const secondaryComplete = Boolean(secondaryHashes["SHA-256"] && secondaryHashes["SHA-512"]); const comparisonReady = mode === "compare" && primaryComplete && secondaryComplete; const matched = comparisonReady && primaryHashes["SHA-256"] === secondaryHashes["SHA-256"] && primaryHashes["SHA-512"] === secondaryHashes["SHA-512"];
  const copy = (value: string) => navigator.clipboard?.writeText(value);
  const exportText = () => { if (!primary || !primaryComplete) return; const describe = (label: string, file: File, hashes: Partial<Hashes>) => `${label}\nFile: ${file.name}\nSize: ${file.size} bytes\nSHA-256: ${hashes["SHA-256"]}\nSHA-512: ${hashes["SHA-512"]}\n`; const content = [describe(mode === "compare" ? "Original file" : "File integrity report", primary, primaryHashes), ...(mode === "compare" && secondary && secondaryComplete ? [describe("Compared file", secondary, secondaryHashes), `Result: ${matched ? "MATCH" : "DIFFERENT"}`] : [])].join("\n"); downloadBlob(new Blob([content], { type: "text/plain;charset=utf-8" }), `${primary.name}-integrity.txt`); };
  return <PublicLayout><main className="container py-10 md:py-14" dir="rtl"><header className="mb-8 flex gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-sky-100 text-sky-700 dark:bg-sky-500/15"><FileCheck2 size={25}/></span><div><p className="text-xs font-bold tracking-[.16em] text-sky-600">LOCAL · INTEGRITY CHECK</p><h1 className="mt-1 text-3xl font-black tracking-tight">{t("فحص سلامة الملف", "File integrity checker")}</h1><p className="mt-2 max-w-2xl text-muted-foreground">{t("اختر حساب بصمة ملف واحد أو مقارنة ملفين مباشرة. كل الحسابات تتم داخل جهازك ولا يُرفع أي ملف إلى خادم.", "Hash one file or compare two files directly. All calculations stay on your device; no file is uploaded.")}</p></div></header>
    <section className="mb-6 grid gap-3 md:grid-cols-2"><ModeCard active={mode === "single"} icon={<FileCheck2 size={22}/>} title={t("حساب بصمة ملف واحد", "Hash one file")} text={t("لإظهار SHA-256 وSHA-512 ونسخهما أو تنزيل تقرير.", "Show SHA-256 and SHA-512, copy them, or download a report.")} onClick={() => { setMode("single"); reset(); }}/><ModeCard active={mode === "compare"} icon={<ArrowLeftRight size={22}/>} title={t("مقارنة ملفين", "Compare two files")} text={t("للتأكد أن النسخة التي لديك مطابقة للملف الأصلي.", "Confirm that the copy you have exactly matches the original.")} onClick={() => { setMode("compare"); reset(); }}/></section>
    <section className="rounded-3xl border bg-card p-5 shadow-sm md:p-7"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">{mode === "single" ? t("الملف المراد حساب بصمته", "File to hash") : t("اختر الملفين للمقارنة", "Choose two files to compare")}</h2><p className="mt-1 text-sm text-muted-foreground">{mode === "single" ? t("سنحسب SHA-256 وSHA-512 معًا.", "We will calculate SHA-256 and SHA-512 together.") : t("تطابق البصمتين يعني أن الملفين متساويان تمامًا.", "Matching both fingerprints means the files are exactly the same.")}</p></div><Button variant="outline" disabled={!primary && !secondary} onClick={() => { setPrimary(undefined); setSecondary(undefined); reset(); }}><X size={16}/>{t("مسح الاختيار", "Clear")}</Button></div><input ref={primaryInput} className="hidden" type="file" onChange={event => assign("primary", event.target.files?.[0])}/><input ref={secondaryInput} className="hidden" type="file" onChange={event => assign("secondary", event.target.files?.[0])}/><div className={`grid gap-4 ${mode === "compare" ? "md:grid-cols-2" : "max-w-2xl"}`}><FilePicker label={mode === "compare" ? t("الملف الأصلي", "Original file") : t("الملف", "File")} file={primary} tone="sky" onChoose={() => primaryInput.current?.click()} onClear={() => { setPrimary(undefined); reset(); }}/>{mode === "compare" && <FilePicker label={t("الملف المراد التحقق منه", "File to verify")} file={secondary} tone="violet" onChoose={() => secondaryInput.current?.click()} onClear={() => { setSecondary(undefined); reset(); }}/>}</div>{working && <div className="mt-5"><div className="mb-2 flex justify-between text-xs text-muted-foreground"><span>{t("جارٍ حساب البصمات محليًا…", "Calculating fingerprints locally…")}</span><span>{Math.round(progress * 100)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-sky-500 transition-all" style={{ width: `${progress * 100}%` }}/></div></div>}<Button className="mt-5" disabled={working || !primary || (mode === "compare" && !secondary)} onClick={compute}><ShieldCheck size={16}/>{mode === "single" ? t("احسب البصمات", "Calculate fingerprints") : t("قارن الملفين", "Compare files")}</Button></section>{error && <p className="mt-5 rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}
    {primaryComplete && <section className="mt-6 grid gap-6 lg:grid-cols-2"><HashCard title={mode === "compare" ? t("بصمة الملف الأصلي", "Original file fingerprints") : t("البصمات المحسوبة", "Calculated fingerprints")} file={primary!} hashes={primaryHashes as Hashes} copy={copy}/>{mode === "compare" && secondaryComplete && <HashCard title={t("بصمة الملف الثاني", "Compared file fingerprints")} file={secondary!} hashes={secondaryHashes as Hashes} copy={copy}/>}</section>}{comparisonReady && <section className={`mt-6 rounded-3xl border p-6 ${matched ? "border-emerald-300 bg-emerald-50/70 dark:bg-emerald-500/10" : "border-amber-300 bg-amber-50/70 dark:bg-amber-500/10"}`}><div className="flex items-start gap-3">{matched ? <Check className="mt-0.5 text-emerald-600"/> : <Files className="mt-0.5 text-amber-700"/>}<div><h2 className="font-black text-lg">{matched ? t("الملفان متطابقان", "The two files match") : t("الملفان مختلفان", "The two files are different")}</h2><p className="mt-1 text-sm text-muted-foreground">{matched ? t("تطابقت بصمتا SHA-256 وSHA-512؛ النسختان متماثلتان على مستوى البايتات.", "Both SHA-256 and SHA-512 match, so the files are byte-for-byte identical.") : t("اختلفت بصمة واحدة على الأقل؛ الملفان ليسا النسخة نفسها.", "At least one fingerprint differs, so these are not the same file.")}</p></div></div></section>}{primaryComplete && <Button className="mt-6" variant="outline" onClick={exportText}><Download size={16}/>{t("تنزيل تقرير TXT", "Download TXT report")}</Button>}<section className="mt-8 rounded-3xl border bg-muted/30 p-5 text-sm leading-7 text-muted-foreground"><b className="text-foreground">{t("كيف تستخدم الأداة؟", "How to use this tool")}</b><p className="mt-2">{mode === "single" ? t("اختر ملفًا ثم اضغط «احسب البصمات». انسخ SHA-256 أو SHA-512 عندما يطلبها منك مصدر موثوق.", "Choose a file, then calculate its fingerprints. Copy SHA-256 or SHA-512 when a trusted source asks for it.") : t("اختر الملف الأصلي والنسخة التي وصلتك ثم اضغط «قارن الملفين». ظهور «متطابقان» يعني أن النسخة لم تتغير.", "Choose the original and the received copy, then compare. A match means the copy has not changed.")}</p></section></main></PublicLayout>;
}

function ModeCard({ active, icon, title, text, onClick }: { active: boolean; icon: React.ReactNode; title: string; text: string; onClick: () => void }) { return <button className={`rounded-3xl border p-5 text-right transition ${active ? "border-sky-500 bg-sky-50/70 shadow-sm dark:bg-sky-500/10" : "bg-card hover:border-sky-300"}`} onClick={onClick}><span className="mb-3 block text-sky-600">{icon}</span><b>{title}</b><p className="mt-1 text-sm text-muted-foreground">{text}</p></button>; }
function FilePicker({ label, file, tone, onChoose, onClear }: { label: string; file?: File; tone: "sky" | "violet"; onChoose: () => void; onClear: () => void }) { return <div className={`rounded-2xl border-2 border-dashed p-5 text-center ${tone === "sky" ? "border-sky-200 bg-sky-50/30" : "border-violet-200 bg-violet-50/30"}`}><Upload className={`mx-auto mb-3 ${tone === "sky" ? "text-sky-600" : "text-violet-600"}`}/><b>{label}</b><p className="mt-2 break-all text-sm text-muted-foreground">{file ? `${file.name} · ${formatBytes(file.size)}` : "—"}</p><div className="mt-4 flex justify-center gap-2"><Button variant="outline" onClick={onChoose}><Upload size={16}/>{file ? "تغيير الملف" : "اختيار ملف"}</Button>{file && <Button size="icon" variant="ghost" onClick={onClear}><X size={16}/></Button>}</div></div>; }
function HashCard({ title, file, hashes, copy }: { title: string; file: File; hashes: Hashes; copy: (value: string) => void }) { return <section className="rounded-3xl border bg-card p-5 shadow-sm"><div className="flex gap-3"><FileCheck2 className="text-sky-600"/><div><h2 className="font-bold">{title}</h2><p className="mt-1 break-all text-sm text-muted-foreground">{file.name} · {formatBytes(file.size)}</p></div></div><div className="mt-5 space-y-3">{(["SHA-256", "SHA-512"] as HashAlgorithm[]).map(algorithm => <div key={algorithm} className="rounded-2xl bg-muted/60 p-4"><div className="flex items-center justify-between gap-2"><b>{algorithm}</b><Button size="sm" variant="ghost" onClick={() => copy(hashes[algorithm])}><Clipboard size={15}/>نسخ</Button></div><code className="mt-2 block break-all text-xs leading-6">{hashes[algorithm]}</code></div>)}</div></section>; }
