import { Button } from "@/components/ui/button";
import PublicLayout from "@/components/PublicLayout";
import ToolCard from "@/components/ToolCard";
import { categories, featuredToolDefinitions, toolDefinitions } from "@/lib/tools";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, ChevronDown, FileImage, FileText, FileUp, LockKeyhole, Sparkles, WandSparkles } from "lucide-react";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { useEffect } from "react";

export default function Home() {
  const { isArabic, t } = useLocale(); const [, navigate] = useLocation(); const { user, loading } = useAuth();
  useEffect(() => { if (!loading && user) navigate("/dashboard"); }, [loading, navigate, user]);
  if (user) return null;
  const catalog = trpc.catalog.list.useQuery(); const managedFaq = trpc.catalog.publicFaq.useQuery({ locale: isArabic ? "ar" : "en" }); const homeContent = trpc.catalog.publicContent.useQuery({ contentKey: "home_notice", locale: isArabic ? "ar" : "en" }); const topAds = trpc.catalog.publicAdSlots.useQuery({ placement: "home_top" }); const featuredBuiltIns = ["qr-generator", "qr-reader", "sign-pdf", "file-hash"]; const activeSlugs = new Set((catalog.data?.length ? catalog.data : toolDefinitions).map((tool: any) => tool.slug).concat(featuredBuiltIns)); const visibleTools = toolDefinitions.filter(tool => activeSlugs.has(tool.slug)); const visiblePopular = featuredToolDefinitions.filter(tool => visibleTools.some(item => item.slug === tool.slug));
  return <PublicLayout><main><section className="hero-section"><div className="hero-grid"/><div className="container relative z-10 py-16 md:py-24"><div className="hero-kicker"><Sparkles size={15}/>{t("منصة أدوات ملفات محلية", "A local file-tools platform")}</div><h1>{t("ملفاتك،", "Your files,")}<span>{t(" بلا تعقيد.", " without friction.")}</span></h1><p className="hero-copy">{t("منصة واحدة لـPDF والصور والمستندات والجداول والرموز. اختر الأداة المناسبة أولًا، ثم عالج ملفاتك داخل متصفحك بوضوح وخصوصية.", "One platform for PDFs, images, documents, spreadsheets and codes. Choose the right tool first, then process files privately in your browser.")}</p>{homeContent.data?.[0] && <p className="managed-home-notice">{homeContent.data[0].title}{homeContent.data[0].body ? ` — ${homeContent.data[0].body}` : ""}</p>}<div className="hero-actions"><a href="#tools" className="hero-cta button button-default">{t("اختر أداة لمعالجة ملفك", "Choose a tool for your file")}<ArrowLeft size={17} className={isArabic ? "rotate-180" : ""}/></a><a href="#categories" className="hero-link">{t("استعرض التصنيفات", "Browse categories")}<ChevronDown size={17}/></a></div><div className="hero-trust"><span><Check size={15}/>{t("لا تسجيل مطلوب", "No sign-up")}</span><span><Check size={15}/>{t("معالجة محلية", "Local processing")}</span><span><Check size={15}/>{t("واجهة عربية", "Arabic-first")}</span></div><a href="#tools" className="quick-drop" aria-label={t("انتقل لاختيار أداة الملفات", "Go to choose a file tool")}><span className="quick-drop-icon"><FileUp size={28}/></span><div><strong>{t("لديك ملف؟ اختر الأداة المناسبة أولًا", "Have a file? Choose the right tool first")}</strong><p>{t("من الصفحة التالية اختر PDF أو الصور أو المستندات أو الجداول؛ لن نربط ملفك بأداة تلقائيًا.", "Choose PDF, images, documents, or spreadsheets below; your file will not be sent to a tool automatically.")}</p></div><span className="quick-drop-button">{t("اختيار أداة", "Choose tool")}</span></a></div><div className="hero-stat-card"><span>{t("مصمم للخصوصية", "Privacy by design")}</span><b>{t("المعالجة داخل جهازك", "Processing on your device")}</b><div className="stat-wave"/></div></section>{topAds.data?.map(slot => <ManagedAdSlot key={slot.id} label={slot.label}/>) }

<section id="tools" className="tools-section container"><div className="section-heading"><div><span className="section-eyebrow">{t("المكتبة", "THE LIBRARY")}</span><h2>{t("اختر ما تحتاجه الآن", "Pick what you need now")}</h2></div><p>{t("ابدأ بنوع ملفك، ثم افتح أداة محددة لرفع الملف ومعالجته. الأدوات غير المستقرة تحمل حالة واضحة ولا تبدأ المعالجة تلقائيًا.", "Start with your file type, then open a specific tool to upload and process it. Unstable tools show a clear status and never start automatically.")}</p></div><div id="categories" className="home-category-cards"><a href="#pdf"><FileText size={20}/><span>{t("PDF", "PDF")}</span><small>{t("دمج، تنظيم، تنقيح", "Merge, organize, redact")}</small></a><a href="#image"><FileImage size={20}/><span>{t("الصور", "Images")}</span><small>{t("تحويل، ضغط، تمويه", "Convert, compress, blur")}</small></a><a href="#document"><FileText size={20}/><span>{t("المستندات", "Documents")}</span><small>{t("Word، نص، تحويل", "Word, text, conversion")}</small></a></div><div className="category-rail">{categories.map(cat => <a href={`#${cat.id}`} key={cat.id}><cat.icon size={17}/>{isArabic ? cat.labelAr : cat.labelEn}</a>)}</div>{categories.map(category => { const items = visibleTools.filter(tool => tool.category === category.id); if (!items.length) return null; return <div id={category.id} className="tool-category" key={category.id}><div className="tool-category-heading"><span className={`tool-icon tool-${category.id}`}><category.icon size={20}/></span><div><h3>{isArabic ? category.labelAr : category.labelEn}</h3><p>{t("اختر أداة ثم ارفع ملفك داخل الصفحة التالية", "Choose a tool, then upload inside the next page")}</p></div><span>{items.length} {t("أدوات", "tools")}</span></div><div className="tools-grid">{items.map((tool, index) => <ToolCard key={tool.slug} tool={tool} index={index}/>)}</div></div>})}</section>

<section className="featured-section"><div className="container"><div className="featured-head"><div><span className="section-eyebrow"><WandSparkles size={14}/>{t("الأكثر استخدامًا", "MOST USED")}</span><h2>{t("ابدأ من هنا", "Start here")}</h2></div><a href="#tools">{t("كل الأدوات", "All tools")}<ArrowLeft size={16} className={isArabic ? "rotate-180" : ""}/></a></div><div className="featured-grid">{visiblePopular.map((tool, index) => <ToolCard key={tool.slug} tool={tool} index={index}/>)}</div></div></section>

<section id="privacy" className="container privacy-section"><div className="privacy-emblem"><LockKeyhole size={28}/></div><div><span className="section-eyebrow">{t("الخصوصية أولًا", "PRIVACY FIRST")}</span><h2>{t("ملفاتك لا تغادر جهازك في الأدوات المحلية.", "Your files stay on your device with local tools.")}</h2></div><p>{t("نوضح في كل صفحة أداة أين تتم المعالجة وحدودها قبل أن تبدأ. لا نخزّن محتوى ملفاتك في أدوات المعالجة المحلية.", "Every tool explains its processing location and limits before you start. Local tools do not store your file content.")}</p><Link href="/privacy"><Button variant="outline">{t("مركز الخصوصية", "Privacy center")}</Button></Link></section>

<section id="faq" className="container faq-section"><div><span className="section-eyebrow">FAQ</span><h2>{t("أسئلة واضحة، إجابات واضحة.", "Clear questions. Clear answers.")}</h2></div><div className="faq-list">{managedFaq.data?.length ? managedFaq.data.map((item, index) => <details key={item.id} open={index === 0}><summary>{item.question}</summary><p>{item.answer}</p></details>) : <DefaultFaq t={t}/>}</div></section></main></PublicLayout>;
}

function ManagedAdSlot({ label }: { label: string }) { return <div className="container managed-ad-slot" role="complementary" aria-label="advertising slot"><span>مساحة إعلان مهيأة</span><b>{label}</b><small>لا يظهر محتوى إعلان أو شيفرة طرف ثالث حتى تتم إضافته من الإدارة مستقبلًا.</small></div>; }
function DefaultFaq({ t }: { t: (ar: string, en: string) => string }) { return <><details open><summary>{t("هل ترفعون ملفي إلى خادم؟", "Do you upload my file?")}</summary><p>{t("لا في الأدوات المعلّمة بمعالجة محلية؛ تعمل داخل متصفحك. نوضح أي معالجة مختلفة بوضوح قبل الاستخدام.", "Not for tools labeled Local: they run in your browser. We clearly label any different processing before use.")}</p></details><details><summary>{t("هل كل التحويلات متطابقة 100%؟", "Are all conversions 100% identical?")}</summary><p>{t("عمليات PDF والصور قوية محليًا. أما تحويل DOCX وPDF المعقد فيعمل بأفضل جهد محلي ولا نعد بتطابق التخطيط.", "PDF and image operations are strong locally. Complex DOCX/PDF conversion is best-effort locally, without a false layout-match promise.")}</p></details><details><summary>{t("هل أحتاج إلى حساب؟", "Do I need an account?")}</summary><p>{t("لا. الأدوات الأساسية متاحة من دون تسجيل دخول. الدخول مطلوب فقط لإدارة المنصة.", "No. Core tools do not require an account. Sign-in is reserved for platform administration.")}</p></details></>; }
