import { Button } from "@/components/ui/button";
import PublicLayout from "@/components/PublicLayout";
import ToolCard from "@/components/ToolCard";
import { categories, featuredToolDefinitions, toolDefinitions } from "@/lib/tools";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, ChevronDown, FileUp, LockKeyhole, Sparkles, WandSparkles } from "lucide-react";
import { Link, useLocation } from "wouter";

export default function Home() {
  const { isArabic, t } = useLocale(); const [, navigate] = useLocation();
  const catalog = trpc.catalog.list.useQuery(); const managedFaq = trpc.catalog.publicFaq.useQuery({ locale: isArabic ? "ar" : "en" }); const homeContent = trpc.catalog.publicContent.useQuery({ contentKey: "home_notice", locale: isArabic ? "ar" : "en" }); const topAds = trpc.catalog.publicAdSlots.useQuery({ placement: "home_top" }); const featuredBuiltIns = ["qr-generator", "qr-reader", "barcode-generator", "sign-pdf", "file-hash"]; const activeSlugs = new Set((catalog.data?.length ? catalog.data : toolDefinitions).map((tool: any) => tool.slug).concat(featuredBuiltIns)); const visibleTools = toolDefinitions.filter(tool => activeSlugs.has(tool.slug)); const visiblePopular = featuredToolDefinitions.filter(tool => visibleTools.some(item => item.slug === tool.slug));
  return <PublicLayout><main><section className="hero-section"><div className="hero-grid"/><div className="container relative z-10 py-16 md:py-24"><div className="hero-kicker"><Sparkles size={15}/>{t("معالجة ذكية. على جهازك.", "Smart processing. On your device.")}</div><h1>{t("ملفاتك،", "Your files,")}<span>{t(" بلا تعقيد.", " without friction.")}</span></h1><p className="hero-copy">{t("حوّل، اضغط، نظّم، واستخرج ما تحتاجه من ملفاتك. معظم الأدوات تعمل داخل متصفحك، من دون رفع الملف إلى خادم.", "Convert, compress, organize and extract what you need. Most tools work right in your browser, without uploading your file.")}</p>{homeContent.data?.[0] && <p className="managed-home-notice">{homeContent.data[0].title}{homeContent.data[0].body ? ` — ${homeContent.data[0].body}` : ""}</p>}<div className="hero-actions"><Link href="/merge-pdf"><Button size="lg" className="hero-cta">{t("ابدأ بملف PDF", "Start with PDF")}<ArrowLeft size={17} className={isArabic ? "rotate-180" : ""}/></Button></Link><a href="#tools" className="hero-link">{t("تصفح كل الأدوات", "Explore all tools")}<ChevronDown size={17}/></a></div><div className="hero-trust"><span><Check size={15}/>{t("لا تسجيل مطلوب", "No sign-up")}</span><span><Check size={15}/>{t("معالجة محلية", "Local processing")}</span><span><Check size={15}/>{t("واجهة عربية", "Arabic-first")}</span></div><button onClick={() => navigate("/image-to-pdf")} className="quick-drop" aria-label={t("افتح أداة الصور إلى PDF", "Open image to PDF")}><span className="quick-drop-icon"><FileUp size={28}/></span><div><strong>{t("اسحب ملفك هنا أو اختر أداة", "Drop a file here or choose a tool")}</strong><p>{t("سنوجّهك إلى الأداة المناسبة حسب نوع الملف.", "We’ll direct you to the right tool for your file type.")}</p></div><span className="quick-drop-button">{t("ابدأ", "Start")}</span></button></div><div className="hero-stat-card"><span>{t("مصمم للخصوصية", "Privacy by design")}</span><b>{t("المعالجة داخل جهازك", "Processing on your device")}</b><div className="stat-wave"/></div></section>{topAds.data?.map(slot => <ManagedAdSlot key={slot.id} label={slot.label}/>) }

<section id="tools" className="tools-section container"><div className="section-heading"><div><span className="section-eyebrow">{t("المكتبة", "THE LIBRARY")}</span><h2>{t("اختر ما تحتاجه الآن", "Pick what you need now")}</h2></div><p>{t("أدوات عملية مرتبة حسب نوع الملف. تظهر الأدوات التي تعمل فعليًا فقط.", "Practical tools, organized by file type. Only tools wired to real functionality are shown.")}</p></div><div className="category-rail">{categories.map(cat => <a href={`#${cat.id}`} key={cat.id}><cat.icon size={17}/>{isArabic ? cat.labelAr : cat.labelEn}</a>)}</div>{categories.map(category => { const items = visibleTools.filter(tool => tool.category === category.id); if (!items.length) return null; return <div id={category.id} className="tool-category" key={category.id}><div className="tool-category-heading"><span className={`tool-icon tool-${category.id}`}><category.icon size={20}/></span><div><h3>{isArabic ? category.labelAr : category.labelEn}</h3><p>{t("معالجة محلية حيثما تسمح التقنية", "Local processing wherever technology allows")}</p></div><span>{items.length} {t("أدوات", "tools")}</span></div><div className="tools-grid">{items.map((tool, index) => <ToolCard key={tool.slug} tool={tool} index={index}/>)}</div></div>})}</section>

<section className="featured-section"><div className="container"><div className="featured-head"><div><span className="section-eyebrow"><WandSparkles size={14}/>{t("الأكثر استخدامًا", "MOST USED")}</span><h2>{t("ابدأ من هنا", "Start here")}</h2></div><Link href="/merge-pdf">{t("كل الأدوات", "All tools")}<ArrowLeft size={16} className={isArabic ? "rotate-180" : ""}/></Link></div><div className="featured-grid">{visiblePopular.map((tool, index) => <ToolCard key={tool.slug} tool={tool} index={index}/>)}</div></div></section>

<section id="privacy" className="container privacy-section"><div className="privacy-emblem"><LockKeyhole size={28}/></div><div><span className="section-eyebrow">{t("الخصوصية أولًا", "PRIVACY FIRST")}</span><h2>{t("ملفاتك لا تغادر جهازك في الأدوات المحلية.", "Your files stay on your device with local tools.")}</h2></div><p>{t("نوضح في كل صفحة أداة أين تتم المعالجة وحدودها قبل أن تبدأ. لا نخزّن محتوى ملفاتك في أدوات المعالجة المحلية.", "Every tool explains its processing location and limits before you start. Local tools do not store your file content.")}</p><Link href="/privacy"><Button variant="outline">{t("مركز الخصوصية", "Privacy center")}</Button></Link></section>

<section id="faq" className="container faq-section"><div><span className="section-eyebrow">FAQ</span><h2>{t("أسئلة واضحة، إجابات واضحة.", "Clear questions. Clear answers.")}</h2></div><div className="faq-list">{managedFaq.data?.length ? managedFaq.data.map((item, index) => <details key={item.id} open={index === 0}><summary>{item.question}</summary><p>{item.answer}</p></details>) : <DefaultFaq t={t}/>}</div></section></main></PublicLayout>;
}

function ManagedAdSlot({ label }: { label: string }) { return <div className="container managed-ad-slot" role="complementary" aria-label="advertising slot"><span>مساحة إعلان مهيأة</span><b>{label}</b><small>لا يظهر محتوى إعلان أو شيفرة طرف ثالث حتى تتم إضافته من الإدارة مستقبلًا.</small></div>; }
function DefaultFaq({ t }: { t: (ar: string, en: string) => string }) { return <><details open><summary>{t("هل ترفعون ملفي إلى خادم؟", "Do you upload my file?")}</summary><p>{t("لا في الأدوات المعلّمة بمعالجة محلية؛ تعمل داخل متصفحك. نوضح أي معالجة مختلفة بوضوح قبل الاستخدام.", "Not for tools labeled Local: they run in your browser. We clearly label any different processing before use.")}</p></details><details><summary>{t("هل كل التحويلات متطابقة 100%؟", "Are all conversions 100% identical?")}</summary><p>{t("عمليات PDF والصور قوية محليًا. أما تحويل DOCX وPDF المعقد فيعمل بأفضل جهد محلي ولا نعد بتطابق التخطيط.", "PDF and image operations are strong locally. Complex DOCX/PDF conversion is best-effort locally, without a false layout-match promise.")}</p></details><details><summary>{t("هل أحتاج إلى حساب؟", "Do I need an account?")}</summary><p>{t("لا. الأدوات الأساسية متاحة من دون تسجيل دخول. الدخول مطلوب فقط لإدارة المنصة.", "No. Core tools do not require an account. Sign-in is reserved for platform administration.")}</p></details></>; }
