import { Button } from "@/components/ui/button";
import PublicLayout from "@/components/PublicLayout";
import { useLocale } from "@/contexts/LocaleContext";
import { ArrowLeft, Presentation, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function PowerPointStudioPage() {
  const { t } = useLocale();
  return <PublicLayout><main className="container py-10 md:py-14"><header className="mb-8 flex gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-violet-100 text-violet-700 dark:bg-violet-500/15 dark:text-violet-300"><Presentation size={25}/></span><div><p className="text-xs font-bold tracking-[.16em] text-violet-600">POWERPOINT · LOCAL ROADMAP</p><h1 className="mt-1 text-3xl font-black tracking-tight">{t("PowerPoint إلى PDF", "PowerPoint to PDF")}</h1><p className="mt-2 max-w-2xl text-muted-foreground">{t("هذه الأداة قيد التحسين قبل إتاحتها. أوقفنا عارض الشرائح المحلي مؤقتًا لأنه تجاوز ذاكرة بناء الإنتاج، ولا نريد تقديم تحويل غير مستقر.", "This tool is being improved before release. Its local slide renderer is temporarily paused because it exceeded production-build memory; we will not ship an unstable conversion.")}</p></div></header><section className="mx-auto max-w-3xl rounded-3xl border bg-card p-8 text-center shadow-sm"><ShieldCheck className="mx-auto mb-4 text-amber-600" size={34}/><h2 className="text-xl font-black">{t("قريبًا — بعد تثبيت مسار محلي موثوق", "Coming soon — after a reliable local path is stabilized")}</h2><p className="mx-auto mt-3 max-w-xl leading-8 text-muted-foreground">{t("لا تُرسل ملفاتك إلى خدمة خارجية ولا نضيف API مدفوعًا. لن نفعّل PDF إلى PowerPoint أو ضغط PPTX أيضًا قبل تحقق جودة حقيقية. استخدم الأدوات المحلية المتاحة الآن أو ارجع إلى الكتالوج.", "Your files are not sent to an external service and no paid API is added. PDF-to-PowerPoint and PPTX compression also remain unavailable until quality is verified. Use available local tools or return to the catalog.")}</p><Button className="mt-6" asChild><Link href="/#tools"><ArrowLeft size={16}/>{t("العودة إلى الأدوات", "Back to tools")}</Link></Button></section></main></PublicLayout>;
}
