import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { Check, Eye, Frame, Grid3X3, Palette, ScanLine, Sparkles } from "lucide-react";
import { makeStyledQrSvg, type QrDotStyle, type QrEyeStyle, type QrFrameStyle } from "@/lib/code-engine";

export type QrTemplateGroup = "official" | "business" | "print" | "social" | "cards" | "stickers";
export type QrFrameGroup = "minimal" | "formal" | "promotional" | "scan";
export type QrTemplate = { id: string; group: QrTemplateGroup; ar: string; en: string; noteAr: string; noteEn: string; dots: QrDotStyle; eyes: QrEyeStyle; frame: QrFrameStyle; dark: string; light: string; gradientTo?: string; label: string; correction: "L" | "M" | "Q" | "H"; margin: number };
export type QrFramePreset = { id: QrFrameStyle; group: QrFrameGroup; ar: string; en: string; noteAr: string; noteEn: string; label: string };

export const qrTemplates: QrTemplate[] = [
  { id: "classic", group: "official", ar: "اعتماد رسمي", en: "Official", noteAr: "مستندات وطلبات", noteEn: "Documents & requests", dots: "square", eyes: "square", frame: "none", dark: "#161326", light: "#ffffff", label: "", correction: "M", margin: 5 },
  { id: "certificate", group: "official", ar: "شهادة", en: "Certificate", noteAr: "شهادات وتحقق", noteEn: "Certificates", dots: "classy", eyes: "ring", frame: "double", dark: "#16233D", light: "#FDFBF4", label: "تحقق من المستند", correction: "H", margin: 7 },
  { id: "heritage", group: "official", ar: "طابع راقٍ", en: "Heritage", noteAr: "هوية رسمية هادئة", noteEn: "Refined official", dots: "classy", eyes: "ring", frame: "double", dark: "#4B3723", light: "#FFF9ED", label: "امسح للتحقق", correction: "H", margin: 7 },
  { id: "policy", group: "official", ar: "سياسة", en: "Policy", noteAr: "لوائح ومعلومات", noteEn: "Policies & info", dots: "vertical", eyes: "square", frame: "brackets", dark: "#243B53", light: "#F6F9FC", label: "اقرأ التفاصيل", correction: "M", margin: 6 },
  { id: "executive", group: "business", ar: "تنفيذي", en: "Executive", noteAr: "عروض واجتماعات", noteEn: "Meetings & decks", dots: "classy-rounded", eyes: "rounded", frame: "card", dark: "#10243E", light: "#FFFFFF", label: "Scan to connect", correction: "H", margin: 6 },
  { id: "commerce", group: "business", ar: "تجاري", en: "Commerce", noteAr: "فواتير ومدفوعات", noteEn: "Invoices & payment", dots: "square", eyes: "ring", frame: "ribbon", dark: "#075985", light: "#F0FDFA", gradientTo: "#0F766E", label: "امسح للدفع", correction: "H", margin: 6 },
  { id: "network", group: "business", ar: "شبكات", en: "Network", noteAr: "بطاقات أعمال", noteEn: "Business cards", dots: "classy-rounded", eyes: "rounded", frame: "card", dark: "#334155", light: "#FFFFFF", label: "تواصل معنا", correction: "H", margin: 6 },
  { id: "invoice", group: "business", ar: "فاتورة", en: "Invoice", noteAr: "تفاصيل الدفع", noteEn: "Payment details", dots: "square", eyes: "ring", frame: "ribbon", dark: "#075985", light: "#F0FDFA", gradientTo: "#0F766E", label: "الدفع الآمن", correction: "H", margin: 7 },
  { id: "print", group: "print", ar: "طباعة عالية التباين", en: "High contrast", noteAr: "مطبوعات واضحة", noteEn: "Clear printing", dots: "square", eyes: "square", frame: "scan", dark: "#0B0B0B", light: "#FFFFFF", label: "امسح الرمز", correction: "H", margin: 9 },
  { id: "poster", group: "print", ar: "ملصق", en: "Poster", noteAr: "فعاليات وعروض", noteEn: "Events & posters", dots: "extra-rounded", eyes: "rounded", frame: "poster", dark: "#7C3AED", light: "#FFFBEB", gradientTo: "#9A3412", label: "امسح للمزيد", correction: "H", margin: 7 },
  { id: "label", group: "print", ar: "ملصق منتج", en: "Product label", noteAr: "عبوات وبطاقات", noteEn: "Packaging", dots: "extra-rounded", eyes: "rounded", frame: "poster", dark: "#0F766E", light: "#F0FDFA", gradientTo: "#115E59", label: "معلومات المنتج", correction: "H", margin: 7 },
  { id: "minimal", group: "print", ar: "أدنى", en: "Minimal", noteAr: "طباعة مدمجة", noteEn: "Compact print", dots: "square", eyes: "square", frame: "scan", dark: "#242424", light: "#FFFFFF", label: "امسح الرمز", correction: "H", margin: 8 },
  { id: "social", group: "social", ar: "اجتماعي", en: "Social", noteAr: "محتوى ومتابعة", noteEn: "Follow & content", dots: "extra-rounded", eyes: "rounded", frame: "badge", dark: "#6D28D9", light: "#FFFFFF", gradientTo: "#9D174D", label: "امسح للتواصل", correction: "H", margin: 7 },
  { id: "creator", group: "social", ar: "صانع محتوى", en: "Creator", noteAr: "روابط ومقاطع", noteEn: "Links & videos", dots: "extra-rounded", eyes: "rounded", frame: "card", dark: "#4C1D95", light: "#FFF7FF", gradientTo: "#312E81", label: "شاهد الآن", correction: "H", margin: 7 },
  { id: "event", group: "social", ar: "فعالية", en: "Event", noteAr: "دعوات وتذاكر", noteEn: "Invites & tickets", dots: "extra-rounded", eyes: "rounded", frame: "poster", dark: "#7C3AED", light: "#FFFBEB", gradientTo: "#9A3412", label: "احجز مكانك", correction: "H", margin: 7 },
  { id: "profile", group: "cards", ar: "بطاقة شخصية", en: "Profile card", noteAr: "بيانات تواصل", noteEn: "Contact details", dots: "classy-rounded", eyes: "ring", frame: "card", dark: "#0F172A", light: "#F8FAFC", label: "أضف جهة الاتصال", correction: "H", margin: 7 },
  { id: "welcome", group: "cards", ar: "ترحيب", en: "Welcome", noteAr: "ضيافة وقوائم", noteEn: "Hospitality", dots: "classy-rounded", eyes: "rounded", frame: "card", dark: "#047857", light: "#ECFDF5", label: "مرحبًا بك", correction: "H", margin: 7 },
  { id: "access", group: "cards", ar: "دخول سريع", en: "Quick access", noteAr: "بوابات وخدمات", noteEn: "Access & service", dots: "vertical", eyes: "square", frame: "brackets", dark: "#243B53", light: "#F6F9FC", label: "امسح للبدء", correction: "M", margin: 6 },
  { id: "sticker", group: "stickers", ar: "ملصق لامع", en: "Bright sticker", noteAr: "تغليف وترويج", noteEn: "Packaging & promo", dots: "classy", eyes: "ring", frame: "seal", dark: "#7E22CE", light: "#FAF5FF", label: "امسحني", correction: "H", margin: 7 },
  { id: "sale", group: "stickers", ar: "عرض", en: "Offer", noteAr: "حملات وتسويق", noteEn: "Campaigns", dots: "square", eyes: "ring", frame: "ribbon", dark: "#075985", light: "#F0FDFA", gradientTo: "#0F766E", label: "اكتشف العرض", correction: "H", margin: 7 },
  { id: "playful", group: "stickers", ar: "مرح", en: "Playful", noteAr: "ملصقات مرنة", noteEn: "Casual stickers", dots: "extra-rounded", eyes: "rounded", frame: "poster", dark: "#7C3AED", light: "#FFFBEB", gradientTo: "#9A3412", label: "امسح وجرّب", correction: "H", margin: 7 },
];

export const qrFramePresets: QrFramePreset[] = [
  { id: "none", group: "minimal", ar: "بلا إطار", en: "No frame", noteAr: "للتصميم النظيف", noteEn: "Clean", label: "" },
  { id: "outline", group: "minimal", ar: "خط دقيق", en: "Fine outline", noteAr: "حد بسيط", noteEn: "Fine border", label: "" },
  { id: "soft", group: "minimal", ar: "ناعم", en: "Soft", noteAr: "حواف هادئة", noteEn: "Gentle corners", label: "" },
  { id: "double", group: "formal", ar: "مزدوج", en: "Double", noteAr: "اعتمادات وشهادات", noteEn: "Certificates", label: "تحقق الآن" },
  { id: "card", group: "formal", ar: "بطاقة", en: "Card", noteAr: "بيانات الأعمال", noteEn: "Business details", label: "تواصل معنا" },
  { id: "seal", group: "formal", ar: "ختم", en: "Seal", noteAr: "ثقة ورسميات", noteEn: "Trust", label: "امسح للتحقق" },
  { id: "brackets", group: "formal", ar: "زوايا", en: "Brackets", noteAr: "مستندات منظمة", noteEn: "Structured docs", label: "اقرأ التفاصيل" },
  { id: "ticket", group: "promotional", ar: "تذكرة", en: "Ticket", noteAr: "فعاليات وعروض", noteEn: "Events", label: "احجز الآن" },
  { id: "badge", group: "promotional", ar: "شارة", en: "Badge", noteAr: "حملات سريعة", noteEn: "Campaigns", label: "امسحني" },
  { id: "ribbon", group: "promotional", ar: "شريط", en: "Ribbon", noteAr: "دعوة للإجراء", noteEn: "Call to action", label: "اكتشف المزيد" },
  { id: "poster", group: "promotional", ar: "ملصق", en: "Poster", noteAr: "لوحات وأكشاك", noteEn: "Posters", label: "امسح للمزيد" },
  { id: "caption", group: "promotional", ar: "عنوان", en: "Caption", noteAr: "بطاقات منتجات", noteEn: "Labels", label: "معلومات إضافية" },
  { id: "scan", group: "scan", ar: "علامات مسح", en: "Scan marks", noteAr: "وضوح على الكاميرا", noteEn: "Camera clear", label: "امسح الرمز" },
  { id: "pill", group: "scan", ar: "حبّة", en: "Pill", noteAr: "قابل للمسح", noteEn: "Scan friendly", label: "Scan me" },
];

const templateGroups: Array<{ id: QrTemplateGroup; ar: string; en: string }> = [{ id: "official", ar: "رسمي", en: "Official" }, { id: "business", ar: "أعمال", en: "Business" }, { id: "print", ar: "طباعة", en: "Print" }, { id: "social", ar: "اجتماعي", en: "Social" }, { id: "cards", ar: "بطاقات", en: "Cards" }, { id: "stickers", ar: "ملصقات", en: "Stickers" }];
const frameGroups: Array<{ id: QrFrameGroup; ar: string; en: string }> = [{ id: "minimal", ar: "أساسي", en: "Minimal" }, { id: "formal", ar: "رسمي", en: "Formal" }, { id: "promotional", ar: "ترويجي", en: "Promotional" }, { id: "scan", ar: "للمسح", en: "Scan" }];

function MiniQr({ dark, light, frame }: Pick<QrTemplate, "dark" | "light" | "frame">) { return <span className={`qr-mini qr-mini-${frame}`} style={{ "--qr-dark": dark, "--qr-light": light } as CSSProperties}><i/><i/><i/><i/><i/><i/><i/><i/><i/></span>; }

function LiveStylePreview({ template }: { template: QrTemplate }) {
  const [svg, setSvg] = useState("");
  useEffect(() => { let alive = true; makeStyledQrSvg("https://wasl.local/qr-style-preview", { size: 180, dark: template.dark, light: template.light, correction: template.correction, dots: template.dots, eyeStyle: template.eyes, frame: template.frame, label: template.label, labelPosition: "bottom", margin: template.margin, gradientFrom: template.gradientTo ? template.dark : undefined, gradientTo: template.gradientTo }).then(value => alive && setSvg(value)).catch(() => alive && setSvg("")); return () => { alive = false; }; }, [template]);
  return <aside className="qr-style-live-preview"><div><span><Eye size={14}/>معاينة قبل التطبيق</span><b>{template.ar}</b><small>{template.noteAr}</small></div><div className="qr-style-live-canvas">{svg ? <div dangerouslySetInnerHTML={{ __html: svg }}/> : <Sparkles size={24}/>}</div><p><ScanLine size={14}/>المعاينة تستخدم رمزًا فعليًا؛ افحص النتيجة النهائية محليًا بعد التطبيق.</p></aside>;
}

export function QrStyleLibrary({ isArabic, activeTemplateId, current, onApplyTemplate, onApplyFrame }: { isArabic: boolean; activeTemplateId?: string; current: Pick<QrTemplate, "dots" | "eyes" | "frame" | "dark" | "light" | "gradientTo" | "correction" | "margin" | "label">; onApplyTemplate: (template: QrTemplate) => void; onApplyFrame: (frame: QrFramePreset) => void; }) {
  const [kind, setKind] = useState<"template" | "frame">("template"); const [templateGroup, setTemplateGroup] = useState<QrTemplateGroup>("official"); const [frameGroup, setFrameGroup] = useState<QrFrameGroup>("formal"); const [hovered, setHovered] = useState(activeTemplateId || "classic");
  const selected = useMemo(() => qrTemplates.find(template => template.id === hovered) || qrTemplates[0], [hovered]);
  const templateItems = qrTemplates.filter(template => template.group === templateGroup); const frameItems = qrFramePresets.filter(frame => frame.group === frameGroup);
  const framePreview = (frame: QrFramePreset): QrTemplate => ({ id: `frame-${frame.id}`, group: "official", ar: frame.ar, en: frame.en, noteAr: frame.noteAr, noteEn: frame.noteEn, dots: current.dots, eyes: current.eyes, frame: frame.id, dark: current.dark, light: current.light, gradientTo: current.gradientTo, label: frame.label || current.label, correction: current.correction, margin: current.margin });
  return <section className="qr-style-library"><div className="qr-style-library-head"><div><span><Palette size={14}/>مكتبة التصاميم</span><h3>قوالب وإطارات جاهزة حسب الاستخدام</h3><p>مرر فوق أي بطاقة لمعاينتها، ثم انقر لتطبيقها على الرمز الحالي.</p></div><div className="qr-library-mode"><button type="button" className={kind === "template" ? "active" : ""} onClick={() => setKind("template")}><Grid3X3 size={15}/>قوالب</button><button type="button" className={kind === "frame" ? "active" : ""} onClick={() => setKind("frame")}><Frame size={15}/>إطارات</button></div></div>
    {kind === "template" ? <div className="qr-style-layout"><div><div className="qr-style-tabs">{templateGroups.map(group => <button type="button" key={group.id} className={templateGroup === group.id ? "active" : ""} onClick={() => setTemplateGroup(group.id)}>{isArabic ? group.ar : group.en}</button>)}</div><div className="qr-style-card-grid">{templateItems.map(template => <button type="button" key={template.id} className={`qr-style-card ${activeTemplateId === template.id ? "selected" : ""}`} onMouseEnter={() => setHovered(template.id)} onFocus={() => setHovered(template.id)} onClick={() => { setHovered(template.id); onApplyTemplate(template); }}><MiniQr dark={template.dark} light={template.light} frame={template.frame}/><span><b>{isArabic ? template.ar : template.en}</b><small>{isArabic ? template.noteAr : template.noteEn}</small></span>{activeTemplateId === template.id && <Check size={15}/>}</button>)}</div></div><LiveStylePreview template={selected}/></div> : <div className="qr-style-layout"><div><div className="qr-style-tabs">{frameGroups.map(group => <button type="button" key={group.id} className={frameGroup === group.id ? "active" : ""} onClick={() => setFrameGroup(group.id)}>{isArabic ? group.ar : group.en}</button>)}</div><div className="qr-style-card-grid">{frameItems.map(frame => { const preview = framePreview(frame); return <button type="button" key={frame.id} className={`qr-style-card ${current.frame === frame.id ? "selected" : ""}`} onMouseEnter={() => setHovered(preview.id)} onFocus={() => setHovered(preview.id)} onClick={() => { setHovered(preview.id); onApplyFrame(frame); }}><MiniQr dark={preview.dark} light={preview.light} frame={frame.id}/><span><b>{isArabic ? frame.ar : frame.en}</b><small>{isArabic ? frame.noteAr : frame.noteEn}</small></span>{current.frame === frame.id && <Check size={15}/>}</button>; })}</div></div><LiveStylePreview template={selected.id.startsWith("frame-") ? selected : framePreview(frameItems[0])}/></div>}
  </section>;
}
