import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLocale } from "@/contexts/LocaleContext";
import { convertDocument } from "@/lib/document-engine";
import { downloadBlob, downloadZip, formatBytes, LocalFileResult, resultPreviewKind, validateLocalFile } from "@/lib/file-utils";
import { transformImages } from "@/lib/image-engine";
import { extractOcr } from "@/lib/ocr-engine";
import { cancelMediaProcessing, mediaInfo, processMedia } from "@/lib/media-engine";
import { alterPdf, comparePdfs, compressPdf, countPdfFormFields, imagesToPdf, mergePdfs, pdfToImages, redactPdf, repairPdf, securePdf } from "@/lib/pdf-engine";
import { trpc } from "@/lib/trpc";
import type { ToolDefinition } from "@/lib/tools";
import { chooseProcessingRoute, serverRouteAvailable } from "@/lib/processing-route";
import { workspaceResultState } from "@/lib/workspace-results";
import { formatSelectedFileCount, mergeFileSelection } from "@/lib/file-queue";
import { matchesToolInput, takePendingFileForTool } from "@/lib/file-handoff";
import { AlertCircle, AudioLines, Ban, CheckCircle2, ChevronDown, ChevronUp, Download, FileArchive, FilePlus2, GripVertical, Image as ImageIcon, Loader2, LockKeyhole, RefreshCw, ShieldCheck, Trash2, UploadCloud, Video, X, Zap } from "lucide-react";
import { ChangeEvent, DragEvent, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";

type WorkspaceOptions = {
  pages: string; rotation: number; watermark: string; watermarkFont: "sans" | "serif" | "mono"; watermarkSize: number; watermarkColor: string; watermarkOpacity: number; watermarkPosition: "center" | "top-left" | "top-right" | "bottom-left" | "bottom-right"; position: "bottom" | "top";
  cropX: number; cropY: number; cropWidth: number; cropHeight: number; blurX: number; blurY: number; blurWidth: number; blurHeight: number; blurRadius: number; width: number; height: number;
  metadataMode: "view" | "clear"; quality: number; password: string;
  outputType: "image/jpeg" | "image/png" | "image/webp"; ocrLanguage: "ara" | "eng" | "ara+eng"; bitrate: string; start: number; end: number; resolution: string; fps: string; flipX: boolean; flipY: boolean;
};
const initialOptions: WorkspaceOptions = { pages: "", rotation: 90, watermark: "", watermarkFont: "sans", watermarkSize: 54, watermarkColor: "#7352f4", watermarkOpacity: .24, watermarkPosition: "center", position: "bottom", cropX: 0, cropY: 0, cropWidth: 500, cropHeight: 700, blurX: 0, blurY: 0, blurWidth: 200, blurHeight: 120, blurRadius: 16, width: 595, height: 842, metadataMode: "view", quality: .82, password: "", outputType: "image/webp", ocrLanguage: "ara+eng", bitrate: "128k", start: 0, end: 15, resolution: "1280:-2", fps: "30", flipX: false, flipY: false };
const initialOptionsFor = (tool: ToolDefinition): WorkspaceOptions => ({ ...initialOptions, quality: tool.slug === "compress-pdf" ? .5 : initialOptions.quality });
const errorText = (error: unknown) => error instanceof Error ? error.message : "تعذر إكمال العملية. تأكد من الملف والإعدادات ثم أعد المحاولة.";
function inputFamily(tool: ToolDefinition): "pdf" | "image" | "document" | "ocr" | "audio" | "video" { if (tool.slug === "image-to-pdf") return "image"; if (tool.slug === "pdf-to-word") return "pdf"; if (tool.category === "pdf" || tool.category === "image" || tool.category === "ocr" || tool.category === "document" || tool.category === "audio" || tool.category === "video") return tool.category; return "document"; }

export default function ToolWorkspace({ tool }: { tool: ToolDefinition }) {
  const { isArabic, t } = useLocale(); const inputRef = useRef<HTMLInputElement>(null); const operationIdRef = useRef(0); const cancelControllerRef = useRef<AbortController | null>(null);
  const auth = useAuth(); const requiresPdfPasswordLogin = tool.slug === "protect-pdf" || tool.slug === "unlock-pdf";
  const [files, setFiles] = useState<File[]>([]); const [results, setResults] = useState<LocalFileResult[]>([]); const [watermarkImage, setWatermarkImage] = useState<string>();
  const [processing, setProcessing] = useState(false); const [progress, setProgress] = useState(0); const [dragging, setDragging] = useState(false); const [queueDragIndex, setQueueDragIndex] = useState<number | null>(null); const [error, setError] = useState<string>(); const [ocrPreview, setOcrPreview] = useState<string>(); const [options, setOptions] = useState<WorkspaceOptions>(() => initialOptionsFor(tool));
  const publicSettings = trpc.catalog.settings.useQuery(); const telemetry = trpc.telemetry.event.useMutation(); const telemetryError = trpc.telemetry.error.useMutation();
  const isPdf = tool.category === "pdf"; const isImage = tool.category === "image"; const accepts = tool.accepts.join(","); const maxFileMb = publicSettings.data?.localMaxFileMb ?? 100; const hybridReady = tool.processingMode === "hybrid"; const serverAvailable = serverRouteAvailable(tool.processingMode, Boolean(publicSettings.data?.serverProcessingEnabled)); const executionRoute = chooseProcessingRoute(tool.processingMode, Boolean(publicSettings.data?.serverProcessingEnabled));
  const selectedSize = useMemo(() => files.reduce((total, file) => total + file.size, 0), [files]); const resultState = useMemo(() => workspaceResultState(results), [results]); const primary = files[0];
  const previewUrl = useMemo(() => primary && (primary.type.startsWith("image/") || primary.type.startsWith("video/") || primary.type.startsWith("audio/") || primary.type === "application/pdf") ? URL.createObjectURL(primary) : undefined, [primary]);
  useEffect(() => () => { if (previewUrl) URL.revokeObjectURL(previewUrl); }, [previewUrl]);
  useEffect(() => { const txt = tool.category === "ocr" ? results.find(result => result.mime === "text/plain") : undefined; if (!txt) { setOcrPreview(undefined); return; } let active = true; void txt.blob.text().then(text => { if (active) setOcrPreview(text); }); return () => { active = false; }; }, [results, tool.category]);
  useEffect(() => { if (publicSettings.data?.analyticsEnabled) telemetry.mutate({ eventType: "tool_open", toolSlug: tool.slug, locale: isArabic ? "ar" : "en", platform: navigator.platform.slice(0, 40), browser: navigator.userAgent.includes("Firefox") ? "Firefox" : navigator.userAgent.includes("Safari") ? "Safari" : "Chromium" }); }, [tool.slug, isArabic, publicSettings.data?.analyticsEnabled]);
  const setOption = <K extends keyof WorkspaceOptions>(key: K, value: WorkspaceOptions[K]) => setOptions(current => ({ ...current, [key]: value }));

  const addFiles = async (incoming: File[]) => {
    setError(undefined); setResults([]); if (!incoming.length) return; const next = tool.multi ? incoming : [incoming[0]];
    try { await Promise.all(next.map(async file => { await validateLocalFile(file, inputFamily(tool), maxFileMb); if (!matchesToolInput(file, tool)) throw new Error("صيغة هذا الملف غير مدعومة لهذه الأداة."); })); setFiles(current => mergeFileSelection(current, next, Boolean(tool.multi))); }
    catch (validationError) { setError(errorText(validationError)); }
  };
  const onInput = (event: ChangeEvent<HTMLInputElement>) => { void addFiles(Array.from(event.target.files || [])); event.target.value = ""; };
  useEffect(() => { const handedOff = takePendingFileForTool(tool.slug); if (handedOff) void addFiles([handedOff]); }, [tool.slug, maxFileMb]);
  const onDrop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setDragging(false); void addFiles(Array.from(event.dataTransfer.files || [])); };
  const moveFile = (index: number, direction: -1 | 1) => setFiles(current => { const destination = index + direction; if (destination < 0 || destination >= current.length) return current; const reordered = [...current]; const [item] = reordered.splice(index, 1); reordered.splice(destination, 0, item); return reordered; });
  const moveFileTo = (from: number, to: number) => setFiles(current => { if (from === to || from < 0 || to < 0 || from >= current.length || to >= current.length) return current; const reordered = [...current]; const [item] = reordered.splice(from, 1); reordered.splice(to, 0, item); return reordered; });
  const processPdf = async () => {
    const report = (amount: number) => setProgress(Math.max(4, Math.round(amount * 100)));
    if (tool.slug === "merge-pdf") return [await mergePdfs(files, report)];
    if (tool.slug === "repair-pdf") return [await repairPdf(files[0], report)];
    if (tool.slug === "compare-pdf") { if (files.length !== 2) throw new Error(t("اختر ملفي PDF بالضبط للمقارنة.", "Choose exactly two PDF files to compare.")); return [await comparePdfs(files[0], files[1], report)]; }
    if (tool.slug === "redact-pdf") return [await redactPdf(files[0], { x: options.cropX, y: options.cropY, width: options.cropWidth, height: options.cropHeight }, report)];
    if (tool.slug === "image-to-pdf") return [await imagesToPdf(files, report)];
    if (tool.slug === "compress-pdf") return [await compressPdf(files[0], options.quality, report)];
    if (tool.slug === "protect-pdf") return [await securePdf(files[0], "protect", options.password, report)];
    if (tool.slug === "unlock-pdf") return [await securePdf(files[0], "unlock", options.password, report)];
    if (tool.slug === "preview-pdf") return [{ name: files[0].name, blob: files[0], mime: "application/pdf", label: "Preview ready" }];
    if (tool.slug === "pdf-to-jpg" || tool.slug === "pdf-to-png") return pdfToImages(files[0], tool.slug.endsWith("jpg") ? "jpeg" : "png", options.quality, report);
    if (tool.slug === "flatten-pdf") { const fieldCount = await countPdfFormFields(files[0]); const outputs = await alterPdf(tool.slug, files[0], { pages: options.pages, rotation: options.rotation, watermark: options.watermark, watermarkSize: options.watermarkSize, watermarkColor: options.watermarkColor, watermarkOpacity: options.watermarkOpacity, watermarkPosition: options.watermarkPosition, position: options.position, crop: { x: options.cropX, y: options.cropY, width: options.cropWidth, height: options.cropHeight }, dimensions: { width: options.width, height: options.height }, metadataMode: options.metadataMode, quality: options.quality }, report); return outputs.map(output => ({ ...output, label: `تم تسطيح ${fieldCount} حقل قابل للتعبئة` })); }
    return alterPdf(tool.slug, files[0], { pages: options.pages, rotation: options.rotation, watermark: options.watermark, watermarkImage, watermarkFont: options.watermarkFont, watermarkSize: options.watermarkSize, watermarkColor: options.watermarkColor, watermarkOpacity: options.watermarkOpacity, watermarkPosition: options.watermarkPosition, position: options.position, crop: { x: options.cropX, y: options.cropY, width: options.cropWidth, height: options.cropHeight }, dimensions: { width: options.width, height: options.height }, metadataMode: options.metadataMode, quality: options.quality }, report);
  };
  const processImage = () => transformImages(files, tool.slug, { outputType: options.outputType, quality: options.quality, width: tool.slug === "resize-image" ? options.width : undefined, height: tool.slug === "resize-image" ? options.height : undefined, keepAspect: true, crop: tool.slug === "crop-image" ? { x: options.cropX, y: options.cropY, width: options.cropWidth, height: options.cropHeight } : undefined, blur: tool.slug === "blur-image" ? { x: options.blurX, y: options.blurY, width: options.blurWidth, height: options.blurHeight, radius: options.blurRadius } : undefined, rotation: tool.slug === "rotate-image" ? options.rotation : 0, flipX: tool.slug === "rotate-image" && options.flipX, flipY: tool.slug === "rotate-image" && options.flipY }, amount => setProgress(Math.max(4, Math.round(amount * 100))));
  const processDocument = () => convertDocument(files[0], tool.slug, amount => setProgress(Math.max(4, Math.round(amount * 100))));
  const processOcr = (signal: AbortSignal) => extractOcr(files, options.ocrLanguage, amount => setProgress(Math.max(4, Math.round(amount * 100))), signal);
  const processMediaTool = async () => (tool.slug === "audio-metadata" || tool.slug === "video-metadata") ? [await mediaInfo(files[0])] : processMedia(files, tool.slug, { bitrate: options.bitrate, start: options.start, end: options.end, resolution: options.resolution, fps: options.fps }, amount => setProgress(Math.max(4, Math.round(amount * 100))));
  const process = async () => {
    if (!files.length) { setError(t("اختر ملفًا واحدًا على الأقل أولًا.", "Choose at least one file first.")); return; }
    if (requiresPdfPasswordLogin && !auth.user) { setError(t("سجّل الدخول لبدء حماية PDF أو فك حمايته.", "Sign in to protect or unlock a PDF.")); return; }
    setProcessing(true); setProgress(3); setError(undefined); setResults([]);
    const operationId = ++operationIdRef.current; const controller = new AbortController(); cancelControllerRef.current = controller; const startedAt = performance.now(); if (publicSettings.data?.analyticsEnabled) telemetry.mutate({ eventType: "process_start", toolSlug: tool.slug, locale: isArabic ? "ar" : "en", sizeBucket: selectedSize < 1_000_000 ? "<1MB" : selectedSize < 10_000_000 ? "1-10MB" : selectedSize < 50_000_000 ? "10-50MB" : "50MB+" });
    try {
      const generated = isPdf ? await processPdf() : isImage ? await processImage() : tool.category === "document" ? await processDocument() : tool.category === "ocr" ? await processOcr(controller.signal) : (tool.category === "audio" || tool.category === "video") ? await processMediaTool() : (() => { throw new Error(t("هذه الأداة لا تملك محرك معالجة مناسبًا.", "This tool does not have a matching processing engine.")); })();
      if (operationId !== operationIdRef.current) return;
      setResults(generated); setProgress(100); if (publicSettings.data?.analyticsEnabled) telemetry.mutate({ eventType: "process_success", toolSlug: tool.slug, locale: isArabic ? "ar" : "en", processingMs: Math.round(performance.now() - startedAt) }); toast.success(tool.slug === "flatten-pdf" ? ((generated[0] as LocalFileResult | undefined)?.label || t("تم تسطيح حقول النموذج داخل جهازك.", "Form fields were flattened on your device.")) : t("اكتملت المعالجة داخل جهازك.", "Processing completed on your device."));
    } catch (processError) { if (operationId !== operationIdRef.current) return; const message = errorText(processError); setError(message); if (publicSettings.data?.analyticsEnabled) { telemetry.mutate({ eventType: "process_error", toolSlug: tool.slug, locale: isArabic ? "ar" : "en", processingMs: Math.round(performance.now() - startedAt) }); telemetryError.mutate({ toolSlug: tool.slug, errorCode: processError instanceof Error ? processError.name.slice(0, 80) : "PROCESS_ERROR", message: "LOCAL_PROCESSING_FAILED" }); } toast.error(t("تعذرت المعالجة", "Processing failed"), { description: message }); }
    finally { if (operationId === operationIdRef.current) { cancelControllerRef.current = null; setProcessing(false); } }
  };
  const cancelProcessing = () => { cancelControllerRef.current?.abort(); if (tool.category === "audio" || tool.category === "video") cancelMediaProcessing(); operationIdRef.current += 1; setProcessing(false); setProgress(0); toast.message(t("أُوقفت المعالجة المحلية وأُهملت النتيجة.", "Local processing was stopped and its result discarded.")); };
  const reset = () => { setFiles([]); setResults([]); setError(undefined); setProgress(0); setWatermarkImage(undefined); setOptions(initialOptionsFor(tool)); };
  const numberField = (label: string, key: "cropX" | "cropY" | "cropWidth" | "cropHeight" | "blurX" | "blurY" | "blurWidth" | "blurHeight" | "blurRadius" | "watermarkSize" | "width" | "height" | "start" | "end", min = 0) => <label className="setting-field"><span>{label}</span><input type="number" min={min} value={options[key]} onChange={event => setOption(key, Number(event.target.value))}/></label>;
  const settings = <div className="workspace-settings"><div className="settings-header"><span>{t("إعدادات الأداة", "Tool settings")}</span><small>{t("تُطبق محليًا", "Applied locally")}</small></div>
    {tool.settings.includes("pages") && <label className="setting-field"><span>{t("الصفحات", "Pages")}</span><input value={options.pages} onChange={event => setOption("pages", event.target.value)} placeholder={t("مثال: 1-3,5", "Example: 1-3,5")}/><small>{tool.slug === "delete-pdf-pages" ? t("الصفحات التي ستُحذف", "Pages to remove") : tool.slug === "reorder-pdf-pages" ? t("اكتب الترتيب المطلوب، مثل: 3,1,2", "Type the preferred order, e.g. 3,1,2") : t("اتركه فارغًا لكل الصفحات", "Leave empty for all pages")}</small></label>}
    {tool.settings.includes("outputFormat") && <label className="setting-field"><span>{t("الصيغة الناتجة", "Output format")}</span><select value={options.outputType} onChange={event => setOption("outputType", event.target.value as WorkspaceOptions["outputType"])}><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select><small>{t("إعادة الترميز تمسح بيانات الصورة الوصفية تلقائيًا.", "Re-encoding strips image metadata automatically.")}</small></label>}
    {tool.settings.includes("rotation") && <label className="setting-field"><span>{t("زاوية التدوير", "Rotation angle")}</span><select value={options.rotation} onChange={event => setOption("rotation", Number(event.target.value))}><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></label>}
    {tool.settings.includes("flip") && <div className="flip-settings"><label><input type="checkbox" checked={options.flipX} onChange={event => setOption("flipX", event.target.checked)}/>{t("قلب أفقي", "Flip horizontally")}</label><label><input type="checkbox" checked={options.flipY} onChange={event => setOption("flipY", event.target.checked)}/>{t("قلب عمودي", "Flip vertically")}</label></div>}
    {tool.settings.includes("watermark") && <><label className="setting-field"><span>{t("نص العلامة المائية", "Watermark text")}</span><input value={options.watermark} onChange={event => setOption("watermark", event.target.value)} placeholder="WASL"/><small>{t("يدعم النص العربي والإنجليزي محليًا. سيُرسم النص العربي كصورة داخل PDF للحفاظ على اتجاهه وتشكيله.", "Arabic and English text are supported locally. Arabic is embedded as an image to preserve direction and shaping.")}</small></label><label className="setting-field"><span>{t("الخط", "Font")}</span><select value={options.watermarkFont} onChange={event => setOption("watermarkFont", event.target.value as WorkspaceOptions["watermarkFont"])}><option value="sans">Sans</option><option value="serif">Serif</option><option value="mono">Mono</option></select></label><label className="setting-field"><span>{t("صورة علامة مائية (اختياري)", "Watermark image (optional)")}</span><input type="file" accept="image/png,image/jpeg" onChange={event => { const image = event.target.files?.[0]; if (!image) return; const reader = new FileReader(); reader.onload = () => setWatermarkImage(typeof reader.result === "string" ? reader.result : undefined); reader.readAsDataURL(image); }}/><small>{watermarkImage ? t("ستُستخدم الصورة بدل النص. يمكنك إزالة الاختيار لإرجاع النص.", "The image will replace the text. Clear the selection to use text again.") : t("PNG أو JPG فقط؛ تبقى الصورة داخل جهازك.", "PNG or JPG only; it stays on your device.")}</small></label><div className="setting-grid">{numberField(t("الحجم", "Size"), "watermarkSize", 10)}<label className="setting-field"><span>{t("اللون", "Color")}</span><input type="color" value={options.watermarkColor} onChange={event => setOption("watermarkColor", event.target.value)}/></label></div><label className="setting-field"><span>{t("الشفافية", "Opacity")} <b>{Math.round(options.watermarkOpacity * 100)}%</b></span><input type="range" min="5" max="95" value={Math.round(options.watermarkOpacity * 100)} onChange={event => setOption("watermarkOpacity", Number(event.target.value) / 100)}/></label><label className="setting-field"><span>{t("الموضع", "Position")}</span><select value={options.watermarkPosition} onChange={event => setOption("watermarkPosition", event.target.value as WorkspaceOptions["watermarkPosition"])}><option value="center">{t("الوسط", "Center")}</option><option value="top-right">{t("أعلى اليمين", "Top right")}</option><option value="top-left">{t("أعلى اليسار", "Top left")}</option><option value="bottom-right">{t("أسفل اليمين", "Bottom right")}</option><option value="bottom-left">{t("أسفل اليسار", "Bottom left")}</option></select></label></>}
    {tool.settings.includes("password") && <label className="setting-field"><span>{tool.slug === "unlock-pdf" ? t("كلمة مرور الملف", "Document password") : t("كلمة المرور الجديدة", "New password")}</span><input type="password" value={options.password} onChange={event => setOption("password", event.target.value)} placeholder="••••••••"/><small>{tool.slug === "protect-pdf" ? t("تنتج هذه العملية نسخة محمية جديدة بإعادة بناء الصفحات مرئيًا.", "This operation creates a protected copy by rebuilding visible pages.") : t("استخدمها فقط عندما تملك كلمة المرور والتصريح.", "Use only when you have the password and authorization.")}</small></label>}
    {tool.settings.includes("pageNumbers") && <label className="setting-field"><span>{t("موضع الترقيم", "Number position")}</span><select value={options.position} onChange={event => setOption("position", event.target.value as "top" | "bottom")}><option value="bottom">{t("أسفل الصفحة", "Bottom")}</option><option value="top">{t("أعلى الصفحة", "Top")}</option></select></label>}
    {tool.settings.includes("quality") && <label className="setting-field"><span>{t("الجودة", "Quality")} <b>{Math.round(options.quality * 100)}%</b></span><input type="range" min="45" max="100" value={Math.round(options.quality * 100)} onChange={event => setOption("quality", Number(event.target.value) / 100)}/><small>{isImage ? t("الجودة الأقل عادة تقلل الحجم أكثر.", "Lower quality usually reduces size more.") : t("قد لا يتغير حجم بعض الملفات لأن النتيجة تعتمد على محتوى الأصل.", "Some files may not shrink because results depend on their original content.")}</small></label>}
    {tool.settings.includes("crop") && <div className="setting-grid">{numberField("X", "cropX")}{numberField("Y", "cropY")}{numberField(t("العرض", "Width"), "cropWidth", 1)}{numberField(t("الارتفاع", "Height"), "cropHeight", 1)}</div>}
    {tool.settings.includes("redaction") && <><div className="setting-grid">{numberField("X", "cropX")}{numberField("Y", "cropY")}{numberField(t("العرض", "Width"), "cropWidth", 1)}{numberField(t("الارتفاع", "Height"), "cropHeight", 1)}</div><small className="block text-xs text-muted-foreground">{t("الإحداثيات بالنقطة من أسفل يسار الصفحة. تُعاد الصفحة كرستر بعد الحجب، لذلك لا يبقى النص أو الرابط الأصلي تحت المنطقة المنقّحة؛ وقد تقل قابلية البحث والجودة قليلًا.", "Coordinates are points from the page’s bottom-left. The page is rasterized after masking, so original text or links do not remain beneath the redaction; searchability and quality may be reduced.")}</small></>}
    {tool.settings.includes("blur") && <><div className="setting-grid">{numberField("X", "blurX")}{numberField("Y", "blurY")}{numberField(t("العرض", "Width"), "blurWidth", 1)}{numberField(t("الارتفاع", "Height"), "blurHeight", 1)}{numberField(t("شدة التمويه", "Blur strength"), "blurRadius", 1)}</div><small className="block text-xs text-muted-foreground">{t("حدّد المنطقة الحساسة بإحداثيات البكسل. هذه أداة يدوية؛ لا تدّعي اكتشاف الوجوه أو لوحات المركبات تلقائيًا.", "Set the sensitive area in pixels. This is a manual tool; it does not claim automatic face or license-plate detection.")}</small></>}
    {tool.settings.includes("dimensions") && <div className="setting-grid">{numberField(t(isImage ? "العرض بالبكسل" : "العرض بالنقطة", isImage ? "Width (px)" : "Width (pt)"), "width", 1)}{numberField(t(isImage ? "الارتفاع بالبكسل" : "الارتفاع بالنقطة", isImage ? "Height (px)" : "Height (pt)"), "height", 1)}</div>}
    {tool.settings.includes("metadata") && <label className="setting-field"><span>{t("بيانات وصف الملف", "Document metadata")}</span><select value={options.metadataMode} onChange={event => setOption("metadataMode", event.target.value as "view" | "clear")}><option value="view">{t("عرض البيانات", "View metadata")}</option><option value="clear">{t("إزالة البيانات", "Remove metadata")}</option></select></label>}
    {tool.settings.includes("language") && <label className="setting-field"><span>{t("لغة OCR", "OCR language")}</span><select value={options.ocrLanguage} onChange={event => setOption("ocrLanguage", event.target.value as WorkspaceOptions["ocrLanguage"])}><option value="ara+eng">{t("العربية والإنجليزية", "Arabic & English")}</option><option value="ara">{t("العربية", "Arabic")}</option><option value="eng">{t("الإنجليزية", "English")}</option></select><small>{t("قد يتطلب أول استخدام تنزيل ملفات اللغة داخل المتصفح.", "The first use may download language data inside your browser.")}</small></label>}
    {tool.settings.includes("bitrate") && <label className="setting-field"><span>{t("معدل البت", "Bitrate")}</span><select value={options.bitrate} onChange={event => setOption("bitrate", event.target.value)}><option value="64k">64 kbps</option><option value="128k">128 kbps</option><option value="192k">192 kbps</option><option value="320k">320 kbps</option></select></label>}
    {tool.settings.includes("trim") && <div className="setting-grid">{numberField(t("البداية بالثواني", "Start seconds"), "start", 0)}{numberField(t("النهاية بالثواني", "End seconds"), "end", 1)}</div>}
    {tool.settings.includes("resolution") && <label className="setting-field"><span>{t("الدقة", "Resolution")}</span><select value={options.resolution} onChange={event => setOption("resolution", event.target.value)}><option value="1920:-2">1080p</option><option value="1280:-2">720p</option><option value="854:-2">480p</option><option value="640:-2">360p</option></select></label>}
    {tool.settings.includes("fps") && <label className="setting-field"><span>FPS</span><select value={options.fps} onChange={event => setOption("fps", event.target.value)}><option value="24">24</option><option value="30">30</option><option value="60">60</option></select></label>}
  </div>;
  return <section className="tool-workspace">
    <div className="tool-workspace-head"><div><span className="local-pill"><LockKeyhole size={12}/>{hybridReady ? serverAvailable ? t("مسار هجين متاح", "Hybrid route available") : t("محلي الآن · جاهز للخادم", "Local now · server-ready") : t("معالجة محلية", "Local processing")}</span><h2>{isArabic ? tool.labelAr : tool.labelEn}</h2><p>{isArabic ? tool.descriptionAr : tool.descriptionEn}</p></div><div className="format-chips">{tool.formats.map(format => <span key={format}>{format}</span>)}</div></div>
    <div className="privacy-inline"><ShieldCheck size={17}/><span>{executionRoute === "server" ? t("المعالجة الخادمية مفعلة لهذه الأداة مع ملف مؤقت محمي وحذف تلقائي بعد انتهاء المدة.", "Server processing is enabled with protected temporary files and automatic expiry.") : hybridReady ? t("تعمل هذه الأداة محليًا الآن. عند تفعيل محرك الخادم مستقبلًا ستختار المنصة المسار الملائم للملفات الكبيرة، مع وظائف مؤقتة ومحميّة فقط.", "This tool runs locally today. Once a server engine is enabled, the platform can select a protected temporary job path for large files.") : t("تتم معالجة ملفك داخل جهازك ولا يتم رفعه إلى خوادمنا.", "Your file is processed on your device and is not uploaded to our servers.")}</span></div>
      <div className="workspace-grid"><div className="workspace-main">
      <div onDrop={onDrop} onDragOver={event => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} className={`drop-zone ${dragging ? "is-dragging" : ""} ${files.length ? "has-files" : ""}`}>
        {files.length ? <><input ref={inputRef} onChange={onInput} type="file" multiple={tool.multi} accept={accepts}/><div className="file-queue">{files.map((file, index) => <div draggable={tool.multi} onDragStart={() => setQueueDragIndex(index)} onDragOver={event => event.preventDefault()} onDrop={() => { if (queueDragIndex !== null) moveFileTo(queueDragIndex, index); setQueueDragIndex(null); }} onDragEnd={() => setQueueDragIndex(null)} className={`queued-file ${queueDragIndex === index ? "is-reordering" : ""}`} key={`${file.name}-${file.lastModified}-${index}`}><span className="file-type-icon"><FileArchive size={18}/></span><div className="min-w-0"><b>{file.name}</b><small>{formatBytes(file.size)}</small></div><div className="queue-actions"><button disabled={index === 0} onClick={() => moveFile(index, -1)} aria-label="move up"><ChevronUp size={15}/></button><button disabled={index === files.length - 1} onClick={() => moveFile(index, 1)} aria-label="move down"><ChevronDown size={15}/></button><button onClick={() => setFiles(current => current.filter((_, itemIndex) => itemIndex !== index))} aria-label="remove"><X size={16}/></button><GripVertical className="queue-grip" size={16}/></div></div>)}<button className="add-more" onClick={() => inputRef.current?.click()}><FilePlus2 size={16}/>{t("إضافة ملف", "Add file")}</button></div></> : <label className="drop-zone-empty"><input ref={inputRef} onChange={onInput} type="file" multiple={tool.multi} accept={accepts}/><span className="drop-icon"><UploadCloud size={29}/></span><strong>{t("اسحب الملف هنا", "Drop your file here")}</strong><span>{t("أو اختره من جهازك", "or choose it from your device")}</span><em>{tool.multi ? t("يمكنك اختيار عدة ملفات", "You can choose multiple files") : t("ملف واحد في كل مرة", "One file at a time")}</em></label>}
      </div>
      {files.length > 0 && <div className="file-summary"><div><span>{t("الملفات المختارة", "Selected files")}</span><b>{formatSelectedFileCount(files.length, isArabic)} · {formatBytes(selectedSize)}</b></div><button onClick={reset}><Trash2 size={14}/>{t("إزالة الكل", "Clear all")}</button></div>}
      {previewUrl && <div className="preview-panel"><div className="preview-label"><ImageIcon size={15}/>{t("معاينة محلية", "Local preview")}</div>{primary?.type.startsWith("image/") && <img src={previewUrl} alt="file preview"/>}{primary?.type.startsWith("audio/") && <audio src={previewUrl} controls/>}{primary?.type.startsWith("video/") && <video src={previewUrl} controls/>}{primary?.type === "application/pdf" && <object className="pdf-preview-object" data={previewUrl} type="application/pdf"><p>{t("يتعذر عرض PDF ضمن المتصفح. يمكنك تنزيله أو فتحه محليًا.", "PDF cannot be previewed in this browser. Download or open it locally.")}</p></object>}</div>}
      </div><aside className="workspace-side">{settings}<Button disabled={!files.length || processing || (requiresPdfPasswordLogin && auth.loading)} onClick={process} className="process-button">{processing ? <><Loader2 className="animate-spin" size={17}/>{t("نعالج الملف…", "Processing…")}</> : <><Zap size={17}/>{requiresPdfPasswordLogin && !auth.loading && !auth.user ? t("سجّل الدخول للمعالجة", "Sign in to process") : t("ابدأ المعالجة", "Process files")}</>}</Button>{requiresPdfPasswordLogin && !auth.loading && !auth.user && <div className="workspace-error"><LockKeyhole size={17}/><span>{t("سجّل الدخول قبل بدء هذه العملية.", "Sign in before starting this operation.")}</span><a href="/login">{t("تسجيل الدخول", "Sign in")}</a></div>}{processing && <><Button variant="outline" onClick={cancelProcessing} className="cancel-process"><Ban size={15}/>{t("إلغاء", "Cancel")}</Button><div className="process-progress"><div><span>{t("التقدم", "Progress")}</span><b>{progress}%</b></div><div className="progress-track"><i style={{ width: `${progress}%` }}/></div><small>{t("يمكن أن تعتمد السرعة على حجم الملف وجهازك. الإلغاء يوقف OCR والوسائط عبر العامل؛ وتُهمل نتائج العمليات الأخرى عند اكتمالها.", "Speed can depend on your device. Cancellation terminates OCR/media workers; other local results are discarded when complete.")}</small></div></>}{error && <div className="workspace-error"><AlertCircle size={17}/><span>{error}</span><button onClick={() => { setError(undefined); void process(); }}><RefreshCw size={14}/>{t("إعادة المحاولة", "Retry")}</button></div>}</aside></div>
    {results.length > 0 && <div className="results-panel"><div className="results-header"><div><span className="result-success"><CheckCircle2 size={17}/>{t("اكتملت النتيجة", "Your result is ready")}</span><p>{t("تم إنشاء الملفات داخل جهازك. اختر التنزيل الذي يناسبك.", "Files were generated on your device. Choose a download below.")}</p></div>{resultState.showZipDownload && <Button variant="outline" onClick={() => void downloadZip(results)}><Download size={15}/>{t("تنزيل الكل ZIP", "Download all ZIP")}</Button>}</div>{ocrPreview !== undefined && <details className="ocr-preview" open><summary>{t("معاينة النص المستخرج محليًا", "Local extracted text preview")}</summary><pre>{ocrPreview.trim() || t("لم يتعرف OCR على نص قابل للاستخراج من هذه العينة.", "OCR did not detect extractable text in this sample.")}</pre></details>}<div className="results-list">{results.map((item, index) => { const original = item.details?.originalSize; return <div className="result-file" key={`${item.name}-${index}`}><ResultPreview item={item}/><div><b>{item.name}</b><small>{typeof original === "number" ? `${formatBytes(original)} → ${formatBytes(item.blob.size)}` : formatBytes(item.blob.size)}{item.details?.compression ? ` · ${item.details.compression}` : ""}</small></div><Button size="sm" onClick={() => downloadBlob(item.blob, item.name)}><Download size={14}/>{t("تنزيل", "Download")}</Button></div>; })}</div><Button variant="ghost" className="new-process" onClick={reset}><RefreshCw size={15}/>{t("بدء عملية جديدة", "Start a new process")}</Button></div>}
  </section>;
}

function ResultPreview({ item }: { item: LocalFileResult }) {
  const kind = resultPreviewKind(item.mime); const url = useMemo(() => kind !== "file" ? URL.createObjectURL(item.blob) : undefined, [item, kind]);
  useEffect(() => () => { if (url) URL.revokeObjectURL(url); }, [url]);
  if (!url) return <span className="file-type-icon"><FileArchive size={18}/></span>;
  if (kind === "image") return <img className="result-thumbnail" src={url} alt=""/>;
  if (kind === "audio") return <span className="result-media-icon"><AudioLines size={18}/></span>;
  return <span className="result-media-icon"><Video size={18}/></span>;
}
